### ISSUE TITLE
Python 3.6 isort not working

### ISSUE THREAD

**Issue by ianepperson** [python-mode/python-mode#1012]
I've been trying to chase this down but I can't get a resolution.

It seems that when adding isort to my virtualenv (`pip install isort`) when I start up pymode in vim I get the following traceback:
```
Traceback (most recent call last)
  File "<string>", line 1, in <module>
  File "/Users/ianepperson/.vim/plugged/python-mode/pymode/lint.py", line 9, in <module>
    from pylama.lint.extensions import LINTERS
  File "/Users/ianepperson/.vim/plugged/python-mode/pymode/libs/pylama/lint/extensions.py", line 55, in <module>
    LINTERS[entry.name] = entry.load()()
  File "/Users/ianepperson/.vim/plugged/python-mode/pymode/libs/pkg_resources/__init__.py", line 2388, in load
    return self.resolve()
  File "/Users/ianepperson/.vim/plugged/python-mode/pymode/libs/pkg_resources/__init__.py", line 2394, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/ianepperson/.virtualenvs/backend/lib/python3.6/site-packages/isort/__init__.py", line 26, in <module>
    from .isort import SortImports  # noqa: F401
  File "/Users/ianepperson/.virtualenvs/backend/lib/python3.6/site-packages/isort/isort.py", line 41, in <module>
    from .finders import FindersManager
  File "/Users/ianepperson/.virtualenvs/backend/lib/python3.6/site-packages/isort/finders.py", line 24, in <module>
    from pip._internal.download import PipSession
  File "/Users/ianepperson/.virtualenvs/backend/lib/python3.6/site-packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/Users/ianepperson/.virtualenvs/backend/lib/python3.6/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/Users/ianepperson/.virtualenvs/backend/lib/python3.6/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/Users/ianepperson/.virtualenvs/backend/lib/python3.6/site-packages/pip/_internal/cli/cmdoptions.py", line 20, in <module>
    from pip._internal.utils.hashes import STRONG_HASHES
  File "/Users/ianepperson/.virtualenvs/backend/lib/python3.6/site-packages/pip/_internal/utils/hashes.py", line 10, in <module>
    from pip._internal.utils.misc import read_chunks
  File "/Users/ianepperson/.virtualenvs/backend/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 21, in <module>
    from pip._vendor import pkg_resources
  File "/Users/ianepperson/.virtualenvs/backend/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3112, in <module>
    @_call_aside
  File "/Users/ianepperson/.virtualenvs/backend/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3096, in _call_aside
    f(*args, **kwargs)
  File "/Users/ianepperson/.virtualenvs/backend/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3140, in _initialize_master_working_set
    for dist in working_set
  File "/Users/ianepperson/.virtualenvs/backend/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3140, in <genexpr>
    for dist in working_set
  File "/Users/ianepperson/.virtualenvs/backend/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2647, in activate
    declare_namespace(pkg)
  File "/Users/ianepperson/.virtualenvs/backend/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2184, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/Users/ianepperson/.virtualenvs/backend/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2101, in _handle_ns
    loader = importer.find_module(packageName)
AttributeError: module 'vim' has no attribute 'find_module'
```

isort otherwise seems to work correctly from the command line.  The above traceback goes away if I uninstall isort.  It looks like the manner in which pylama is pulling in isort is causing isort to throw an exception.  For now, I'll just uninstall isort ( 👎 ) but I would like to use it someday.  I opened this issue for anyone else seeing the above stacktrace without knowing about this issue.

**Comment by rchildre3** [comment]
Could not reproduce

Environemt:
```
vim: 8.0.1453-1ubuntu1 (Huge version without GUI)
distro: Ubuntu 18.04.2 LTS
python: 3.6.7-1~18.04
isort: 4.3.16
python-mode: 7a449a5ee505bbabf4d16ad78ce67a087840d2e9
```
Steps:
```sh
cd ~/.vim/pack/python-mode/start/python-mode
git pull
git submodule update
cd ~
mkdir test
cd test
python3 -m venv env
. ./env/bin/activate
pip install isort
vim -i NONE -u ~/.vim/pack/python-mode/start/python-mode/debugvimrc.vim a.py
```

@diraol Possible duplicate of #916 / #923 / #937 ?

**Comment by diraol** [comment]
@ianepperson can you try removing all "cache files" by going into python-mode directory and running:
```
find . -type f -name '*.pyc' -delete && find . -type d -name '__pycache__' -delete
```
And then make sure that you have the latest version of python-mode and its submodules:
```
git fetch --all
git pull
git submodule sync --recursive
```

**Comment by ianepperson** [comment]
OK, more info.

Environment:
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec 28 2018 20:12:37)
macOS version
Included patches: 1-650
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
...

OSX: 10.14.3 (18D42)

Python 3.6.5

isort: 4.3.16

python-mode: 7a449a5ee505bbabf4d16ad78ce67a087840d2e9 (HEAD -> develop, origin/develop, origin/HEAD)

Installed with Plug:
Plug 'python-mode/python-mode',      { 'for': 'python', 'branch': 'develop' }
Plug 'ambv/black',                   { 'for': 'python', 'do': '. ~/.vim/black/bin/activate; pip install --upgrade black' }
```

@diraol Good idea!  But I followed the steps and have the same result.  After pip installing `isort` (and performing no other action), when I open a Python file within Vim I still get the above trace (one line at a time).  `pip uninstall isort` and I no longer get the traceback when opening a Python file in Vim.

I just recently fixed my `Black` code formatter issues by updating its pet virtualenv - could a virtualenv mismatch be the problem here?  I'm only installing isort in a project virtualenv and not globally.
