### ISSUE TITLE
Error detected while processing lint vim 

### ISSUE THREAD

**Issue by tiantengfei** [python-mode/python-mode#1043]
The following is the messages:
    ```
Error detected while processing /Users/tiantengfei/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Error detected while processing /Users/tiantengfei/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing /Users/tiantengfei/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/tiantengfei/.vim/bundle/python-mode/pymode/lint.py", line 9, in <module>
Error detected while processing /Users/tiantengfei/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Error detected while processing /Users/tiantengfei/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/tiantengfei/.vim/bundle/python-mode/pymode/libs/pylama/lint/extensions.py", line 44, in <module>
Error detected while processing /Users/tiantengfei/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.pylama_pylint import Linter
Error detected while processing /Users/tiantengfei/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/tiantengfei/.vim/bundle/python-mode/pymode/libs/pylama/lint/pylama_pylint.py", line 5, in <module>
Error detected while processing /Users/tiantengfei/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from astroid import MANAGER
Error detected while processing /Users/tiantengfei/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/tiantengfei/.vim/bundle/python-mode/pymode/libs/astroid/__init__.py", line 59, in <module>
Error detected while processing /Users/tiantengfei/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from astroid.exceptions import *
Error detected while processing /Users/tiantengfei/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/tiantengfei/.vim/bundle/python-mode/pymode/libs/astroid/exceptions.py", line 13, in <module>
Error detected while processing /Users/tiantengfei/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from astroid import util
Error detected while processing /Users/tiantengfei/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/tiantengfei/.vim/bundle/python-mode/pymode/libs/astroid/util.py", line 148
Error detected while processing /Users/tiantengfei/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    yield from islice(iterator, size)
Error detected while processing /Users/tiantengfei/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
             ^
Error detected while processing /Users/tiantengfei/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
SyntaxError: invalid syntax
```

python version: 3.4.6
vim version: Vi IMproved 8.1 (2018 May 18, compiled Jul 22 2018 15:18:22)
macOs Mojave 10.14.15
sys.version_info(major=2, minor=7, micro=15, releaselevel='final', serial=0)
no virtual environment

**Comment by amcgregor** [comment]
Platform: macOS Catalina Public Release 10.15.1 (19B88), iMac (Retina 5K, 27-inch, Late 2015).

```
:version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 30 2019 11:57:56)
macOS version
Included patches: 1-2234
Compiled by travis@Traviss-Mac.local
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +byte_offset       +conceal           -ebcdic            +folding           +jumplist          +lua/dyn           +mouse_netterm     +num64             +python/dyn        -sound             -tcl               +toolbar           +vreplace          -xsmp
+arabic            +channel           +cryptv            +emacs_tags        -footer            +keymap            +menu              +mouse_sgr         +odbeditor         +python3/dyn       +spell             +termguicolors     +transparency      +wildignore        -xterm_clipboard
+autocmd           +cindent           +cscope            +eval              +fork()            +lambda            +mksession         -mouse_sysmouse    +packages          +quickfix          +startuptime       +terminal          +user_commands     +wildmenu          -xterm_save
+autochdir         +clientserver      +cursorbind        +ex_extra          +fullscreen        +langmap           +modify_fname      +mouse_urxvt       +path_extra        +reltime           +statusline        +terminfo          +vartabs           +windows
-autoservername    +clipboard         +cursorshape       +extra_search      -gettext           +libcall           +mouse             +mouse_xterm       +perl/dyn          +rightleft         -sun_workshop      +termresponse      +vertsplit         +writebackup
+balloon_eval      +cmdline_compl     +dialog_con_gui    -farsi             -hangul_input      +linebreak         +mouseshape        +multi_byte        +persistent_undo   +ruby/dyn          +syntax            +textobjects       +virtualedit       -X11
+balloon_eval_term +cmdline_hist      +diff              +file_in_path      +iconv             +lispindent        +mouse_dec         +multi_lang        +postscript        +scrollbind        +tag_binary        +textprop          +visual            -xfontset
+browse            +cmdline_info      +digraphs          +find_in_path      +insert_expand     +listcmds          -mouse_gpm         -mzscheme          +printer           +signs             -tag_old_static    +timers            +visualextra       +xim
++builtin_terms    +comments          +dnd               +float             +job               +localmap          -mouse_jsbterm     +netbeans_intg     +profile           +smartindent       -tag_any_white     +title             +viminfo           -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/read
line/lib  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework AppKit   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE

:PymodeVersion
Pymode version: 0.9.4 interpreter: python3 lint: 1 rope: 0
```

Installed via `brew cask install macvim` ([formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/macvim.rb)) with Python 2 and 3 supplied via `brew install python python@2`, with `.vim` and `.vimrc` from my [dotfiles](https://github.com/amcgregor/dotfiles/tree/dotfiles/.vim).  (Python-mode included via Git submodule.)

**Comment by diraol** [comment]
Hi Alice, by including python-mode using submodule you are probably not cloning python-mode submodules too.

That's the reason it is failing for you, missing submodules.

I'd suggest you to avoid this approach and go with a standard vim plugin install approach, much easier :)

**Comment by amcgregor** [comment]
It was my understanding that handling submodules of submodules was the purpose of the `--recursive` flag.  If I'm wrong about that, that'd explain a lot!  ;)  Example invocation to update my `dotfiles` repo submodules:

```sh
git submodule update --remote --checkout --recursive
```

> standard vim plugin install approach

There is one?  Like, really?  _Really_ really?  Because the very first statement from the [installation instructions](https://github.com/python-mode/python-mode#manually-according-to-vims-package-structure) fails:

```sh
cd ~/.vim/pack/python-mode/start
cd: no such file or directory: /Users/amcgregor/.vim/pack/python-mode/start
```

And this would be the first plugin/module I utilize (of 30 or so) to make use of this "native" mechanism.  Tonight I'll give it a go if I can figure it out—I'll migrate the lot—but I do not hold out much hope.  (I've had to disable breakpoints and linting in order to regain usability; can't waste the time to skip 30 error message lines every time I save—failure to lint—and a dozen every time I open a file—breakpoints.)

**Comment by diraol** [comment]
Have you "inited" the submodules recursively too?


By "standard approach" I was refeering to "use a plugin manager", such as "Plug" (or Vundle or Pathogen)

**Comment by amcgregor** [comment]
There is no recursive option to init; nor any options of any kind according to `--help`.  Notice the overlap when cloning:

```
git clone --recurse-submodules git@github.com:python-mode/python-mode.git 2>/dev/null

Submodule path 'submodules/astroid': checked out '5b5cd7acbecaa9b587b07de27a3334a2ec4f2a79'
Submodule path 'submodules/autopep8': checked out '159bb88843e298534e46914da242e680a1c8c47d'
Submodule path 'submodules/mccabe': checked out 'c2f5b386458cfda0aa4239f4d11b4e5e75027bda'
Submodule path 'submodules/pycodestyle': checked out '566cdc0cb22e5530902e456d0b315403ebab980c'
Submodule path 'submodules/pydocstyle': checked out 'eea4ca179553189a7b8a62d6085f15b50bb98e35'
Submodule path 'submodules/pyflakes': checked out '45fc732466056fe35c85936ff25491df7905c597'
Submodule path 'submodules/pylama': checked out '837ecd3d7a8597ab5f28bc83072de68e16470f1e'
Submodule path 'submodules/pylint': checked out '66cb32187c040f82dd067bc0d226b2f105bf6c38'
Submodule path 'submodules/rope': checked out '95aa2749f978d579fda03478dece4d611c2323f9'
Submodule path 'submodules/six': checked out '84d07dd19523a3a41385f23a744a126d00a72c79'
Submodule path 'submodules/snowball_py': checked out '404cab3e069cd5c2c891c19404fbd85bd285c021'
```

```
git clone --recurse-submodules git@github.com:amcgregor/dotfiles.git 2>/dev/null

Submodule path '.vim/bundle/Apprentice': checked out '1226b9a9b001616045dfc10f059e4be067bcbd0d'
Submodule path '.vim/bundle/Conque-Shell': checked out '837586b7a4d6ab03970d74b2bb8a923dfc30fcc5'
Submodule path '.vim/bundle/a.vim': checked out '2cbe946206ec622d9d8cf2c99317f204c4d41885'
Submodule path '.vim/bundle/ag': checked out '4a0dd6e190f446e5a016b44fdaa2feafc582918e'
Submodule path '.vim/bundle/apiblueprint.vim': checked out '776b9863e32a8ba59bf8a9656770a77c148c6e9c'
Submodule path '.vim/bundle/auto-pairs': checked out '39f06b873a8449af8ff6a3eee716d3da14d63a76'
Submodule path '.vim/bundle/coveragepy.vim': checked out '321ea3603ad7cbf672667ec44f8d0b09825a3e8a'
Submodule path '.vim/bundle/ctrlp': checked out '2e773fd8c7548526853fff6ee2e642eafbbe3d04'
Submodule path '.vim/bundle/git-blame.vim': checked out '9d144b7bed5d8f1c9259551768b7f3b3d1294917'
Submodule path '.vim/bundle/nerdtree': checked out '184fbb6ffea6dc69726b229a08153c9d08522386'
Submodule path '.vim/bundle/nerdtree-git-plugin': checked out '0501cdfbe3064d1f2d0987929565bccee5f5a6a5'
Submodule path '.vim/bundle/promptline': checked out '106418570a0ecc33b35439e24b051be34f829b94'
Submodule path '.vim/bundle/pytest.vim': checked out '847aa6f95e3e87a32fd0aa8ff8fb04653123d277'
Submodule path '.vim/bundle/python-mode': checked out '3206441437a58c9ef9d0e40cc12a7e29fdf4d0b9'
Submodule path '.vim/bundle/python-mode/submodules/astroid': checked out '32c96a687ad0e5c59f7c1800bc2e00af26b16d0b'
Submodule path '.vim/bundle/python-mode/submodules/autopep8': checked out '2e7e3ba985bfa7e090a10c6450454ff4b87f9475'
Submodule path '.vim/bundle/python-mode/submodules/mccabe': checked out 'ae9f6b9e2799daa80dad937d9462628b354dab97'
Submodule path '.vim/bundle/python-mode/submodules/pycodestyle': checked out '566cdc0cb22e5530902e456d0b315403ebab980c'
Submodule path '.vim/bundle/python-mode/submodules/pydocstyle': checked out '7f5303c8f9c19010253e350a8d513c0f330226a0'
Submodule path '.vim/bundle/python-mode/submodules/pyflakes': checked out '9dd73ec54411a563410872b47e76f0f89f34ecfe'
Submodule path '.vim/bundle/python-mode/submodules/pylama': checked out 'eb1a13278ebec25d1a75d8779696ab1bf65620fe'
Submodule path '.vim/bundle/python-mode/submodules/pylint': checked out '2b24ec063a5355648d286633e37f084ced4f1604'
Submodule path '.vim/bundle/python-mode/submodules/rope': checked out '97b94211375c3e34d1ca7af27680a429964f474a'
Submodule path '.vim/bundle/python-mode/submodules/snowball_py': checked out '0949a1609dcd59995ae0e30ae2bb644a1aeae744'
Submodule path '.vim/bundle/tagbar': checked out '387bbadda98e1376ff3871aa461b1f0abd4ece70'
Submodule path '.vim/bundle/vim-airline': checked out 'a40184536b3b93b6272585da9c36dca802d47a01'
Submodule path '.vim/bundle/vim-airline-themes': checked out 'b85165844240fe0b9121df487679a320e053abc7'
Submodule path '.vim/bundle/vim-easymotion': checked out '85e90c9759e14633d878ed534ef313876ab96555'
Submodule path '.vim/bundle/vim-eunuch': checked out 'e066a0999e442d9d96f24ad9d203b1bd030ef72e'
Submodule path '.vim/bundle/vim-fugitive': checked out '79b1f16a7adf38ed5e202e5317cc1eabc9399528'
Submodule path '.vim/bundle/vim-git-flow-format': checked out 'b183afc08426cde774c2a131a34f25657066b330'
Submodule path '.vim/bundle/vim-gitgutter': checked out '609b2170bf68531a722217e38088d0fb11f8ec12'
Submodule path '.vim/bundle/vim-javascript': checked out '7cc6baebaf0065fd8c31cc9216c87bfa543eb71a'
Submodule path '.vim/bundle/vim-jdaddy': checked out 'fccddca8092ca3dfa843e9e33fc7be8c8ef1c727'
Submodule path '.vim/bundle/vim-markdown': checked out 'da5a7ac96f517e0fd6f886bc3fbe27156ca1f946'
Submodule path '.vim/bundle/vim-ragtag': checked out '5d3ce9c1ae2232170a3f232c1e20fa832d15d440'
Submodule path '.vim/bundle/vim-rhubarb': checked out 'c509c7eedeea641f5b0bdae708581ff610fbff5b'
Submodule path '.vim/bundle/vim-surround': checked out 'fab8621670f71637e9960003af28365129b1dfd0'
Submodule path '.zsh/plugin/comp': checked out 'b512d57b6d0d2b85368a8068ec1a13288a93d267'
Submodule path '.zsh/plugin/highlight': checked out '35c8690c0025ceef9584f64da86ced3a72ee32b6'
```

In my many, many years of using Vim (ye gods, what a way to feel old) I have never intentionally utilized a "plugin manager".  _Technically_ I think there's one Pathogen plugin in my set, and Pathogen itself.  Though now that I look into it, those can be removed—I don't actually use that Textmate snippets emulation at all.

I'll give "proper plugin management" a go this week-end—a complete refactor of the integration of 28 top-level plugins, woo!—though the proliferation of multiple approaches to this does not inspire confidence—and python-mode is the only one with issues.

**Comment by diraol** [comment]
Hi @amcgregor were you able to make it work after all?

Python mode have many issues, some of them due to supporting python2, among other things.

Over [here](https://github.com/python-mode/python-mode/issues/935#issuecomment-554782399) you can see what I think is the best way to start improving python-mode. Any help would be very very welcome! :)

**Comment by amcgregor** [comment]
@diraol Apologies for the delay.  After a few attempts re-cloning my dotfiles repo with various recursive options, and attempting a variety of post-clone submodule update invocations, I appear to have managed to silence most of the errors which frequently interrupt workflow.  E.g. a page of exception on each save/write.  I haven't managed to restore complete functionality, yet, nor silence errors when initially opening Python source files, get automatic import ordering working, and `rope` integration is basically a complete loss—and my extensive use of venvs aren't helping matters.  Still working on it.  ^_^;

**Comment by diraol** [comment]
Hi @amcgregor !
Thanks for the feedback.

Re-reading this thread I've noticed that I left pass the fact that you are using vim compiled with support to both python2 and 3.

As I've stated in #1053 vim does not work nicely with both versions at the same time.

Would you mind trying with only one version?

Also, today I've just accepted an MR and updated our code base to drop python2 support. Would you mind testing it again? Thanks!
