### ISSUE TITLE
Error detected while processing function provider#python3#Call:

### ISSUE THREAD

**Issue by ghost** [python-mode/python-mode#1070]
The problem appears when I try to open any .py file. I had tried the step from FAQ but nothing changed:
`find . -type f -iname '*.pyc' -o -iname '*.pyo' -delete && find . -type d -name '__pycache__' -delete`
I use the Neovim but the same problem is in the Vim.

OS: ManjaroLinux 18.1.5 x86_64
Kernel: Linux 5.4.13-3-MANJARO

vim --version
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan  7 2020 22:53:41)
Included patches: 1-100
Compiled by Arch Linux
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_old_static
+arabic            +file_in_path      +mouse_urxvt       -tag_any_white
+autocmd           +find_in_path      +mouse_xterm       +tcl/dyn
+autochdir         +float             +multi_byte        +termguicolors
-autoservername    +folding           +multi_lang        +terminal
-balloon_eval      -footer            -mzscheme          +terminfo
+balloon_eval_term +fork()            +netbeans_intg     +termresponse
-browse            +gettext           +num64             +textobjects
++builtin_terms    -hangul_input      +packages          +textprop
+byte_offset       +iconv             +path_extra        +timers
+channel           +insert_expand     +perl/dyn          +title
+cindent           +job               +persistent_undo   -toolbar
-clientserver      +jumplist          +popupwin          +user_commands
-clipboard         +keymap            +postscript        +vartabs
+cmdline_compl     +lambda            +printer           +vertsplit
+cmdline_hist      +langmap           +profile           +virtualedit
+cmdline_info      +libcall           +python/dyn        +visual
+comments          +linebreak         +python3/dyn       +visualextra
+conceal           +lispindent        +quickfix          +viminfo
+cryptv            +listcmds          +reltime           +vreplace
+cscope            +localmap          +rightleft         +wildignore
+cursorbind        +lua/dyn           +ruby/dyn          +wildmenu
+cursorshape       +menu              +scrollbind        +windows
+dialog_con        +mksession         +signs             +writebackup
+diff              +modify_fname      +smartindent       -X11
+digraphs          +mouse             -sound             -xfontset
-dnd               -mouseshape        +spell             -xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        +mouse_gpm         +statusline        -xsmp
+eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary        
   system vimrc file: "/etc/vimrc"
        user vimrc file: "$HOME/.vimrc"
         2nd user vimrc file: "~/.vim/vimrc"
               user exrc file: "$HOME/.exrc"
                      defaults file: "$VIMRUNTIME/defaults.vim"
                        fall-back for $VIM: "/usr/share/vim"
                        Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
                        Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.30/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim        -lm -ltinfo -lelf -lnsl    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.30/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.30/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm     
```

python --version
`Python 3.8.1`

:PymodePython import sys; print(sys.version_info)
```sys.version_info(major=3, minor=8, micro=1, releaselevel='final', serial=0)```

messages from vim
```
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/storm/.vim/plugged/python-mode/pymode/lint.py", line 9, in <module>
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/pylama/lint/extensions.py", line 44, in <module>
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.pylama_pylint import Linter
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/pylama/lint/pylama_pylint.py", line 5, in <module>
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    from astroid import MANAGER
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/__init__.py", line 156, in <module>
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    __import__(module[:-3])
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/brain/brain_builtin_inference.py", line 103, in <module>
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    extend_builtins({'bytes': partial(_extend_str, rvalue="b''"),
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/brain/brain_builtin_inference.py", line 99, in extend_builtins
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    transform(builtin_ast[class_name])
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/brain/brain_builtin_inference.py", line 84, in _extend_str
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    fake = AstroidBuilder(MANAGER).string_build(code)['whatever']
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/builder.py", line 132, in string_build
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    module = self._data_build(data, modname, path)
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/builder.py", line 173, in _data_build
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    module = builder.visit_module(node, modname, node_file, package)
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/rebuilder.py", line 162, in visit_module
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    newnode.postinit([self.visit(child, newnode) for child in node.body])
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/rebuilder.py", line 162, in <listcomp>
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    newnode.postinit([self.visit(child, newnode) for child in node.body])
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/rebuilder.py", line 174, in visit
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    return visit_method(node, parent)
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/rebuilder.py", line 954, in visit_classdef
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    return super(TreeRebuilder3, self).visit_classdef(node, parent,
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/rebuilder.py", line 394, in visit_classdef
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    [self.visit(child, newnode)
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/rebuilder.py", line 394, in <listcomp>
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    [self.visit(child, newnode)
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/rebuilder.py", line 174, in visit
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    return visit_method(node, parent)
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/rebuilder.py", line 576, in visit_functiondef
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    return self._visit_functiondef(nodes.FunctionDef, node, parent)
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/rebuilder.py", line 566, in _visit_functiondef
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    body=[self.visit(child, newnode) for child in node.body],
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/rebuilder.py", line 566, in <listcomp>
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    body=[self.visit(child, newnode) for child in node.body],
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/rebuilder.py", line 174, in visit
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    return visit_method(node, parent)
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/rebuilder.py", line 741, in visit_return
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    newnode.postinit(self.visit(node.value, newnode))
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/rebuilder.py", line 172, in visit
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    visit_method = getattr(self, visit_name)
Error detected while processing /home/storm/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
AttributeError: 'TreeRebuilder3' object has no attribute 'visit_constant'
```

messages from nvim
```
Error detected while processing function provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/storm/.vim/plugged/python-mode/pymode/lint.py", line 9, in <module>
    from pylama.lint.extensions import LINTERS
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/pylama/lint/extensions.py", line 44, in <module>
    from pylama.lint.pylama_pylint import Linter
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/pylama/lint/pylama_pylint.py", line 5, in <module>
    from astroid import MANAGER
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/__init__.py", line 156, in <module>
    __import__(module[:-3])
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/brain/brain_builtin_inference.py", line 103, in <module>
    extend_builtins({'bytes': partial(_extend_str, rvalue="b''"),
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/brain/brain_builtin_inference.py", line 99, in extend_builtins
    transform(builtin_ast[class_name])
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/brain/brain_builtin_inference.py", line 84, in _extend_str
    fake = AstroidBuilder(MANAGER).string_build(code)['whatever']
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/builder.py", line 132, in string_build
    module = self._data_build(data, modname, path)
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/builder.py", line 173, in _data_build
    module = builder.visit_module(node, modname, node_file, package)
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/rebuilder.py", line 162, in visit_module
    newnode.postinit([self.visit(child, newnode) for child in node.body])
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/rebuilder.py", line 162, in <listcomp>
    newnode.postinit([self.visit(child, newnode) for child in node.body])
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/rebuilder.py", line 174, in visit
    return visit_method(node, parent)
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/rebuilder.py", line 954, in visit_classdef
    return super(TreeRebuilder3, self).visit_classdef(node, parent,
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/rebuilder.py", line 394, in visit_classdef
    [self.visit(child, newnode)
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/rebuilder.py", line 394, in <listcomp>
    [self.visit(child, newnode)
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/rebuilder.py", line 174, in visit
    return visit_method(node, parent)
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/rebuilder.py", line 576, in visit_functiondef
    return self._visit_functiondef(nodes.FunctionDef, node, parent)
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/rebuilder.py", line 566, in _visit_functiondef
    body=[self.visit(child, newnode) for child in node.body],
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/rebuilder.py", line 566, in <listcomp>
    body=[self.visit(child, newnode) for child in node.body],
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/rebuilder.py", line 174, in visit
    return visit_method(node, parent)
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/rebuilder.py", line 741, in visit_return
    newnode.postinit(self.visit(node.value, newnode))
  File "/home/storm/.vim/plugged/python-mode/pymode/libs/astroid/rebuilder.py", line 172, in visit
    visit_method = getattr(self, visit_name)
AttributeError: 'TreeRebuilder3' object has no attribute 'visit_constant'
```

**Comment by diraol** [comment]
Hi @Storm-Sergey, please take a look at this comment: https://github.com/python-mode/python-mode/issues/1053#issuecomment-564069826

**Comment by Storm-Sergey** [comment]
> Hi @Storm-Sergey, please take a look at this comment: [#1053 (comment)](https://github.com/python-mode/python-mode/issues/1053#issuecomment-564069826)

Excuse me, could you give a hint how can I do that?

**Comment by ghost** [comment]
@diraol 
Excuse me, could you give a hint how can I do that? I mean what should I do if I only use python 3?

**Comment by diraol** [comment]
Hi @Storm-Sergey basically you need to have vim installed with only python3 support.

That would require building vim from the source code (IIRC some OS package managers just have vim with support to both python2 and 3 at the same time).

This is a nice reference that I usually go to when I need to do it:

 - https://github.com/ycm-core/YouCompleteMe/wiki/Building-Vim-from-source

**Comment by ghost** [comment]
After building from the sources the problem is gone.
@diraol Thank you!
