### ISSUE TITLE
No module named 'pkg_resources'

### ISSUE THREAD

**Issue by Liripo** [python-mode/python-mode#1081]
Dear developer：
 I encountered the following error and don't know how to solve it.
```python
Error detected while processing /home/liripo/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing /home/liripo/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing /home/liripo/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/liripo/.vim/plugged/python-mode/pymode/lint.py", line 9, in <module>
Press ENTER or type command to continue
Error detected while processing /home/liripo/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Press ENTER or type command to continue
Error detected while processing /home/liripo/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/liripo/.vim/plugged/python-mode/pymode/libs/pylama/lint/extensions.py", line 56, in <module>
Press ENTER or type command to continue
Error detected while processing /home/liripo/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    from pkg_resources import iter_entry_points
Press ENTER or type command to continue
Error detected while processing /home/liripo/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by diraol** [comment]
Hi @Liripo sorry for the late answer.

Can you follow the [Troubleshooting](https://github.com/python-mode/python-mode#troubleshootingdebugging) section and give us some more info about your setup, please?

**Comment by kevinqli** [comment]
Did this issue ever get resolved? I'm encountering the same error message.
