### ISSUE TITLE
Problem with internal method, autocomplete and lint.

### ISSUE THREAD

**Issue by diabloneo** [python-mode/python-mode#576]
When I use internal method inside a class bound method, two problems occus:
1. Auto complete stop working. After I typing _self._, I got message _-- Omni completion (^O^N^P) Pattern not found_.
2. Lint when I write the file failed, error message is as follows:

```
[Pymode] Code checking is running ...
Error detected while processing function pymode#buffer_post_write..pymode#lint#check:
line   11:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/diabloneo/.vim/bundle/python-mode/pymode/lint.py", line 71, in code_check
    env.run('g:PymodeLocList.current().extend', [e._info for e in errors])
  File "/home/diabloneo/.vim/bundle/python-mode/pymode/environment.py", line 186, in run
    self.prepare_value(a) for a in args
vim.error: Vim(call):E121: Undefined variable: null
Error detected while processing function pymode#buffer_post_write:
line   10:
E171: Missing :endif
```
##

**Comment by diabloneo** [comment]
Additional information:

Only the last method in a class has this problem:

```
Class C(object):
    def method1(self):
        def inner():
            pass

        # it's ok here

    def method2(self):
        def inner():
            pass

        # it's not ok here
```

**Comment by diabloneo** [comment]
Sorry, I misreported this issue. I use jedi + pymode, the auto complate problem is jedi's.
