### ISSUE TITLE
Error detected while processing function pymode#lint#check

### ISSUE THREAD

**Issue by CipherChen** [python-mode/python-mode#577]
Um, it's weird.

When I run `PymodeLint` to a specific piece of code, 

```
def xyz(description=None, count):

    return ""
```

It tells me:

```
[Pymode] Code checking is running ...
Error detected while processing function pymode#lint#check:
line   11:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/CipherChen/CIPHERC/configs/vim/vim/bundle/python-mode/pymode/lint.py", line 62, in code_check
    env.run('g:PymodeLocList.current().extend', [e._info for e in errors])
  File "/Users/CipherChen/CIPHERC/configs/vim/vim/bundle/python-mode/pymode/environment.py", line 178, in run
    self.prepare_value(a) for a in args
vim.error: Vim(call):E121: Undefined variable: null
Press ENTER or type command to continue
```

However, the following file wouldn't cause the exception:

```
def xyz(count, description=None):

    return ""
```

Any idea?
##

**Comment by mapler** [comment]
I've got the same error when 
```from foo import bar, ```
while ```from foo import bar``` is ok.
