### ISSUE TITLE
ImportError in pylama in develop branch

### ISSUE THREAD

**Issue by wilywampa** [python-mode/python-mode#597]
When I try to run `PymodeLint` in the develop branch after af4268183a9a005da6ea37874f720ae90e64ff3b I get a screen full of errors because `node_classes.py` can't find `logilab.common.decorators`:

```
Error detected while processing /Users/jniehus/Documents/vimconfig/vimfiles/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/python-mode/pymode/lint.py", line 10, in <module>
    from pylama.lint.pylama_pylint import Linter
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/python-mode/pymode/libs/pylama/lint/pylama_pylint/__init__.py", line 12, in <module>
    from .main import Linter  # noqa
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/python-mode/pymode/libs/pylama/lint/pylama_pylint/main.py", line 9, in <module>
    from astroid import MANAGER
  File "./vimfiles/bundle/python-mode/pymode/libs/pylama/lint/pylama_pylint/astroid/__init__.py", line 51, in <module>

  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/python-mode/pymode/libs/astroid/__init__.py", line 54, in <module>
    from astroid.nodes import *
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/python-mode/pymode/libs/astroid/nodes.py", line 41, in <module>
    from astroid.node_classes import Arguments, AssAttr, Assert, Assign, \
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/python-mode/pymode/libs/astroid/node_classes.py", line 24, in <module>
    from logilab.common.decorators import cachedproperty
ImportError: No module named logilab.common.decorators
```
##

**Comment by asazello** [comment]
Same error.

**Comment by wilywampa** [comment]
It looks like just __init__.py was missing: https://github.com/klen/python-mode/pull/598

**Comment by wilywampa** [comment]
Adding the file silenced the obvious errors but didn't actually fix the problem so I closed the PR.

**Comment by madmadcat** [comment]
I found the same error and the solution was touch a empty __init__.py in logilab directory.

**Comment by klen** [comment]
I don't have the issue, but I've add `__init__.py` to logilab directory. Please ping me if the error still appears.
