### ISSUE TITLE
Pylama KeyError when linting

### ISSUE THREAD

**Issue by bordeltabernacle** [python-mode/python-mode#709]
I am using Neovim version 0.2.0-dev, and the most recent version of python-mode via vim-plug. I have started to get the following error pop up every time I make a change and save a .py file.

```
[Pymode] Code checking is running ...
Error detected while processing function pymode#buffer_post_write[10]..pymode#lint#check[11]..provider#python3#Call:
line   18:
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/home/rob/dotfiles/.vim/plugged/python-mode/pymode/lint.py", line 27, in code_check
    force=1,

  File "/home/rob/dotfiles/.vim/plugged/python-mode/pymode/libs/pylama/config.py", line 149, in parse_options
    cfg = get_config(str(options.options))

  File "/home/rob/dotfiles/.vim/plugged/python-mode/pymode/libs/pylama/config.py", line 210, in get_config
    config.read(path)

  File "/home/rob/dotfiles/.vim/plugged/python-mode/pymode/libs/pylama/libs/inirama.py", line 309, in read
    self.parse(ff.read(), **params)

  File "/home/rob/dotfiles/.vim/plugged/python-mode/pymode/libs/pylama/libs/inirama.py", line 364, in parse
    self[section][name] += '\n' + token[1].strip()

KeyError: 'omit'
[Pymode] Code checking is completed. No errors found.
[Pymode] Found errors and warnings: 0
```

My python-mode .vimrc settings:

```
let g:pymode = 1
let g:pymode_trim_whitespaces = 1
let g:pymode_options = 1
let g:pymode_options_max_line_length = 79
let g:pymode_quickfix_minheight = 3
let g:pymode_quickfix_maxheight = 6
let g:pymode_python = 'python3'
let g:pymode_indent = 1
let g:pymode_folding = 1
let g:pymode_motion = 1
let g:pymode_doc = 1
let g:pymode_doc_bind = 'K'
let g:pymode_virtualenv = 0
let g:pymode_run = 1
let g:pymode_run_bind = '<leader>pr'
let g:pymode_lint = 1
let g:pymode_lint_on_write = 1
let g:pymode_lint_message = 1
let g:pymode_lint_checkers = ['flake8', 'pylint']
let g:pymode_lint_ignore = "E501,F0002,E116"
let g:pymode_lint_cwindow = 1
let g:pymode_lint_signs = 1
let g:pymode_rope = 0
let g:pymode_syntax = 1
let g:pymode_syntax_all = 1
let g:pymode_syntax_print_as_function = 1
let g:pymode_syntax_indent_errors = g:pymode_syntax_all
let g:pymode_syntax_space_errors = g:pymode_syntax_all
let g:pymode_syntax_string_formatting = g:pymode_syntax_all
let g:pymode_syntax_string_format = g:pymode_syntax_all
let g:pymode_syntax_string_templates = g:pymode_syntax_all
let g:pymode_syntax_doctests = g:pymode_syntax_all
```

Nothing seems to be broken per se, but this error message appearing every time I save is annoying, obvs. If I can help let me know, but I don't know where the `omit` key is coming from.

**Comment by bordeltabernacle** [comment]
Well, it's been bugging me all day, I report it and I've had a glass of wine and now it's just gone away.
¯\_(ツ)_/¯
Thanks for the code sir, you're making life better :+1:

**Comment by bordeltabernacle** [comment]
Sorry, it's back. I'll see what I maybe did differently for it to disappear, but if you're able to shed some light that would be great.

**Comment by bordeltabernacle** [comment]
So, it's something to do with my `setup.cfg` file in the root of my project directory.
If I move the following lines from the beginning of the file to the end, then the error goes away:

```
[coverage:run]
omit=tests/* ,*/__init__.py
```
