### ISSUE TITLE
Errors during startup of vim python file editing, python version is 2.7.12

### ISSUE THREAD

**Issue by se77en** [python-mode/python-mode#716]
Traceback is:

```
Error detected while processing /Users/ariesdevil/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Error detected while processing /Users/ariesdevil/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing /Users/ariesdevil/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/ariesdevil/.vim/bundle/python-mode/pymode/lint.py", line 9, in <module>
Error detected while processing /Users/ariesdevil/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Error detected while processing /Users/ariesdevil/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/ariesdevil/.vim/bundle/python-mode/pymode/libs/pylama/lint/extensions.py", line 30, in <module>
Error detected while processing /Users/ariesdevil/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pkg_resources import iter_entry_points
Error detected while processing /Users/ariesdevil/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/ariesdevil/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 21, in <module>
Error detected while processing /Users/ariesdevil/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    import io
Error detected while processing /Users/ariesdevil/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/usr/local/var/pyenv/versions/2.7.12/lib/python2.7/io.py", line 51, in <module>
Error detected while processing /Users/ariesdevil/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    import _io
Error detected while processing /Users/ariesdevil/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
ImportError: dlopen(/usr/local/var/pyenv/versions/2.7.12/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
Error detected while processing /Users/ariesdevil/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  Referenced from: /usr/local/var/pyenv/versions/2.7.12/lib/python2.7/lib-dynload/_io.so
Error detected while processing /Users/ariesdevil/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  Expected in: flat namespace
Error detected while processing /Users/ariesdevil/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
 in /usr/local/var/pyenv/versions/2.7.12/lib/python2.7/lib-dynload/_io.so
```

**Comment by brycepg** [comment]
Possible duplicate of  #403
