### ISSUE TITLE
PymodeLint does not run / NvimError:  Vim(let):E121: Undefined variable: u    

### ISSUE THREAD

**Issue by zartstrom** [python-mode/python-mode#722]
`:PymodeLint` does not run, if I do `:PymodeTroubleshooting` I get this error message:

```
Error detected while processing function pymode#troubleshooting#test[50]..provider#python#Call:                        
line   18:                                                                                                             
Traceback (most recent call last):                                                                                     
  File "<string>", line 2, in <module>                                                                                 
  File "/usr/lib/python2.7/site-packages/neovim/api/nvim.py", line 218, in command                                     
    return self.request('nvim_command', string, **kwargs)                                                              
  File "/usr/lib/python2.7/site-packages/neovim/api/nvim.py", line 131, in request                                     
    res = self._session.request(name, *args, **kwargs)                                                                 
  File "/usr/lib/python2.7/site-packages/neovim/msgpack_rpc/session.py", line 98, in request                           
    raise self.error_wrapper(err)                                                                                      
NvimError: Vim(let):E121: Undefined variable: u                                                                        
Error detected while processing function pymode#troubleshooting#test:                                                  
line   50:                                                                                                             
E171: Missing :endif
```
```
» uname -a
Linux yuki 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux
```
```
» pacman -Q | grep neovim
neovim 0.1.7-2
python2-neovim 0.1.12-2
```
python-mode is up to date (ran `:PlugUpdate`).

Has anybody experience with this?

**Comment by zartstrom** [comment]
Hi @selurvedu , cool! I'm sure it is worth a PR, although I can't judge if there are any hidden implications in this (small) change.

**Comment by lyager** [comment]
+1 was debugging if I could use pycodestyle tool, but I'm unable to run PymodeTroubleshooting on both Vim8 and NeoVim

**Comment by fmv1992** [comment]
I have changed the the troubleshooting file to something different. I believe that makes the bug go away.

Feel free to reopen the issue!

**Comment by selurvedu** [comment]
@fmv1992 thanks for freeing me from a tiny task I was postponing over and over. ;)

For reference: https://github.com/python-mode/python-mode/commit/6d497a405a66096ef5c0b51fd7ce260236ea5fda

**Comment by fmv1992** [comment]
I'm glad to help!
