### ISSUE TITLE
PymodeLintAuto fails

### ISSUE THREAD

**Issue by pazz** [python-mode/python-mode#752]
I'm trying to use `PymodeLintAuto` and am getting the following error message.
I've just updated Pymode via vundle (github) 
Is this a python3 vs 2 thing?
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pazz/.vim/bundle/python-mode/pymode/__init__.py", line 27, in auto
    fix_file(vim.current.buffer.name, Options)
  File "/home/pazz/.vim/bundle/python-mode/pymode/autopep8.py", line 2961, in fix_file
    fixed_source = fix_lines(fixed_source, options, filename=filename)
  File "/home/pazz/.vim/bundle/python-mode/pymode/autopep8.py", line 2922, in fix_lines
    filename=filename)
  File "/home/pazz/.vim/bundle/python-mode/pymode/autopep8.py", line 3006, in apply_global_fixes
    for code in ['E101', 'E111']):
  File "/home/pazz/.vim/bundle/python-mode/pymode/autopep8.py", line 3006, in <genexpr>
    for code in ['E101', 'E111']):
  File "/home/pazz/.vim/bundle/python-mode/pymode/autopep8.py", line 2851, in code_match
    assert not isinstance(ignore, unicode)
AssertionError
```

**Comment by pazz** [comment]
This problem does not occur after a `:let g:pymode_lint_ignore = ""`

**Comment by CraneJen** [comment]
@pazz  
me too

**Comment by madjxatw** [comment]
Same here, only occurs for python3, no problem for python2. 
String in Python2 has two style: **str** and **unicode**, the string that Vim transfers to Py2 is in **str** style, so the assert statement passes. 
Python3 has no **unicode** style, but a **bytes** class which is equivalent to **str** in Python2, and **str**  in Py3 is equivalent to **unicode** in Py2. Did some test and found that the data transferred from Vim to python3 is **str** (=unicode) not **bytes**.

As `autopep8.py` has:
```python
try:
    unicode  # only works for python2
except NameError:
    unicode = str  # for python3, name unicode as str
```
so the assert statement fails for python3. I just simply comment out the unicode assertions to make the LintAuto function work for both. but not sure if it will break something else.

**Comment by jennaliu** [comment]
PymodeLintAuto works for me. If you type
`:python3 import sys`
`:python3 print(sys.version)`
What is the output?
If python3 doesn't work, try
`:python import sys`
`:python print(sys.version)`
