### ISSUE TITLE
Frequent traceback on save

### ISSUE THREAD

**Issue by zacps** [python-mode/python-mode#775]
This trace-back happens frequently, but not always while linting

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/zacpullarstrecker/.config/nvim/plugged/python-mode/pymode/lint.py", line 46, in code_check
    if 'pylint' in options.linters_params:
KeyError: 'pylint'
```
Output of `call pymode#troubleshooting#test()`
```
Pymode diagnostic
===================
VIM:704, OS: Linux, multi_byte:1, pymode: 0.9.2, pymode-python: python


+python: 1
+python3: 1

VIM python paths:
-----------------
/home/zacpullarstrecker/.config/nvim/plugged/python-mode/pymode/libs
/home/zacpullarstrecker/.config/nvim/plugged/python-mode
/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/home/zacpullarstrecker/.local/lib/python2.7/site-packages
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/gtk-2.0
_vim_path_
/home/zacpullarstrecker/.config/nvim/plugged/python-mode/pymode/libs/astroid/brain
.
..

Pymode variables:
-------------------
let pymode = 1
let pymode_breakpoint = 1
let pymode_breakpoint_bind = '<leader>b'
let pymode_doc = 1
let pymode_doc_bind = 'K'
let pymode_folding = 1
let pymode_indent = 1
let pymode_lint = 1
let pymode_lint_checkers = ['pyflakes', 'pep8', 'mccabe']
let pymode_lint_cwindow = 1
let pymode_lint_ignore = ''
let pymode_lint_message = 1
let pymode_lint_on_fly = 0
let pymode_lint_on_write = 1
let pymode_lint_select = ''
let pymode_lint_signs = 1
let pymode_motion = 1
let pymode_options = 1
let pymode_paths = []
let pymode_quickfix_maxheight = 6
let pymode_quickfix_minheight = 3
let pymode_rope = 0
let pymode_run = 1
let pymode_run_bind = '<leader>r'
let pymode_trim_whitespaces = 1
let pymode_virtualenv = 1
let pymode_virtualenv_enabled = ''
let pymode_virtualenv_path = ''
```
Output of `:CheckHealth`
```

health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - INFO: Build type: None
  - WARNING: Non-optimized build-type. Nvim will be slower.
    - SUGGESTIONS:
      - Install a different Nvim package, or rebuild with `CMAKE_BUILD_TYPE=RelWithDebInfo`.
      - See https://github.com/neovim/neovim/wiki/FAQ

## Remote Plugins
  - SUCCESS: Up to date

## terminfo
  - INFO: key_backspace terminfo entry: key_backspace=\177,

health#provider#check
========================================================================
## Clipboard
  - SUCCESS: Clipboard tool found: xsel

## Python 2 provider
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python2 version: 2.7.12
  - INFO: python2-neovim version: 0.1.13
  - SUCCESS: Latest python2-neovim is installed: 0.1.13

## Python 3 provider
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python3 version: 3.5.2
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider
  - ERROR: Missing Neovim RubyGem
    - SUGGESTIONS:
      - Install or upgrade the neovim RubyGem using `gem install neovim`.
  - INFO: Ruby Version: ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
  - INFO: Host Executable: not found
  - INFO: Host Version: not found

```

**Comment by fmv1992-bot-account** [comment]
Warning: this issue has been inactive for 131 days and will be automatically closed on 2018-01-17 if there is no further activity.
