### ISSUE TITLE
python-mode/pymode/libs/configparser.py breaks pycodestyle.py

### ISSUE THREAD

**Issue by hawkeyej** [python-mode/python-mode#803]
When I try to run "python pycodestyle.py -h" from the python-mode/pymode/libs directory, I get this:
```
Traceback (most recent call last):
  File "pycodestyle.py", line 64, in <module>
    from configparser import RawConfigParser
  File "/home/jeff/.vim/bundle/python-mode/pymode/libs/configparser.py", line 12, in <module>
    from backports.configparser import (
ModuleNotFoundError: No module named 'backports.configparser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pycodestyle.py", line 67, in <module>
    from ConfigParser import RawConfigParser
ModuleNotFoundError: No module named 'ConfigParser'
```
Renaming codeparser.py in that directory to something else fixes the problem.

PymodeTroubleshooting info
```
Pymode diagnostic
===================
VIM:800, OS: Linux, multi_byte:1, pymode: 0.9.2, pymode-python: python3


+python: 0
+python3: 1

VIM python paths:
-----------------
/home/<me>/.vim/bundle/python-mode/pymode/libs
/home/<me>/.vim/bundle/python-mode
/home/<me>/poit-sdi/toolbox
/home/<me>/anaconda3/lib/python36.zip
/home/<me>/anaconda3/lib/python3.6
/home/<me>/anaconda3/lib/python3.6/lib-dynload
/home/<me>/anaconda3/lib/python3.6/site-packages
_vim_path_
/home/<me>/.vim/bundle/riv.vim/autoload/riv/

Pymode variables:
-------------------
let pymode = 1
let pymode_breakpoint = 1
let pymode_breakpoint_bind = '<leader>b'
let pymode_doc = 1
let pymode_doc_bind = 'K'
let pymode_folding = 1
let pymode_indent = 1
let pymode_lint = 1
let pymode_lint_checkers = ['pep8', 'flake8', 'mccabe']
let pymode_lint_cwindow = 1
let pymode_lint_ignore = ''
let pymode_lint_message = 1
let pymode_lint_on_fly = 0
let pymode_lint_on_write = 1
let pymode_lint_select = ''
let pymode_lint_signs = 1
let pymode_motion = 1
let pymode_options = 1
let pymode_paths = []
let pymode_quickfix_maxheight = 16
let pymode_quickfix_minheight = 6
let pymode_rope = 0
let pymode_run = 1
let pymode_run_bind = '<leader>r'
let pymode_trim_whitespaces = 1
let pymode_virtualenv = 1
let pymode_virtualenv_enabled = ''
let pymode_virtualenv_path = ''
```

**Comment by fmv1992** [comment]
@hawkeyej,

I encourage you to read the following issue.

https://github.com/python-mode/python-mode/issues/805

Moving to submodules might fix this problem (and several others). Let me know if it helps.

**Comment by fmv1992** [comment]
Actually this clash makes sense. You are running a module which should import from somewhere else but because there is a file in $PWD that has the same name it imports from the wrong place.

Not vim's nor this plugins fault.
