### ISSUE TITLE
Error detected while processing ~/.vim/bundle/python-mode/autoload/pymode/lint.vim

### ISSUE THREAD

**Issue by regisz** [python-mode/python-mode#908]
Hi,

I get the next error messages if I open a py file:
```
Error detected while processing /home/balage/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Error detected while processing /home/balage/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing /home/balage/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/balage/.vim/bundle/python-mode/pymode/lint.py", line 9, in <module>
Error detected while processing /home/balage/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Error detected while processing /home/balage/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/balage/.vim/bundle/python-mode/pymode/libs/pylama/lint/extensions.py", line 12, in <module>
Error detected while processing /home/balage/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.pylama_pydocstyle import Linter
Error detected while processing /home/balage/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/balage/.vim/bundle/python-mode/pymode/libs/pylama/lint/pylama_pydocstyle.py", line 6, in <module>
Error detected while processing /home/balage/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pydocstyle import ConventionChecker as PyDocChecker
Error detected while processing /home/balage/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/balage/.vim/bundle/python-mode/pymode/libs/pydocstyle/__init__.py", line 1, in <module>
Error detected while processing /home/balage/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from .checker import check
Error detected while processing /home/balage/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/balage/.vim/bundle/python-mode/pymode/libs/pydocstyle/checker.py", line 17, in <module>
Error detected while processing /home/balage/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from .wordlists import IMPERATIVE_VERBS, IMPERATIVE_BLACKLIST, stem
Error detected while processing /home/balage/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/balage/.vim/bundle/python-mode/pymode/libs/pydocstyle/wordlists.py", line 9, in <module>
Error detected while processing /home/balage/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    import snowballstemmer
Error detected while processing /home/balage/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/balage/.vim/bundle/python-mode/pymode/libs/snowballstemmer/__init__.py", line 3, in <module>
Error detected while processing /home/balage/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from .danish_stemmer import DanishStemmer
Error detected while processing /home/balage/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/balage/.vim/bundle/python-mode/pymode/libs/snowballstemmer/danish_stemmer.py", line 15
Error detected while processing /home/balage/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    Among(u"hed", -1, 1),
Error detected while processing /home/balage/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
               ^
Error detected while processing /home/balage/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
SyntaxError: invalid syntax
```
$ vim --version
```
VIM - Vi IMproved 8.1 (2018 May 17, compiled Jun 19 2018 13:26:45)
Compiled by balage
Huge version without GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
+autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               -perl              +vertsplit
-clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           +python/dyn        +vreplace
+conceal           +linebreak         +python3/dyn       +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       -lua               -ruby              -X11
+dialog_con        +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             -xim
+digraphs          +modify_fname      +smartindent       -xpm
-dnd               +mouse             +startuptime       -xsmp
-ebcdic            -mouseshape        +statusline        -xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              -mouse_gpm         +syntax
+ex_extra          -mouse_jsbterm     +tag_binary
+extra_search      +mouse_netterm     +tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/home/balage/.local/share/vim"
Compilation: gcc -std=gnu99 -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -std=gnu99   -L/usr/local/lib -Wl,--as-needed -o vim        -lm -ltinfo -lnsl    -ldl
```

$ lsb_release -a
```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.11 (wheezy)
Release:        7.11
Codename:       wheezy
```

**Comment by diraol** [comment]
Please, follow this:

https://github.com/python-mode/python-mode#troubleshootingdebugging

**Comment by regisz** [comment]
The problem was the default python version. In the a92bfa4764 commit the default python version has been changed to python3. And, unfortunately, on server of my company (debian wheezy, an old system, but it can not be upgraded) the py3 version is 3.2.3, and if I know well, this is not a good py3 version.
So, I put into my .vimrc  `let g:pymode_python = 'python'`, and everything is ok again :).

**Comment by amckinlay** [comment]
@regisz Might want to change the readme.

**Comment by hawkeyej** [comment]
This happens far too often:
```
Error detected while processing /home/jeff/.vim/bundle/python-mode/autoload/pymode/lint.vim
```
Sometimes I can figure out how to fix it (delete *.pyc sometime works) and other times I can't.
It's very frustrating, as I do a lot of python work.

**Comment by diraol** [comment]
Please guys, let's not revive old threads without adding new contents or with messages that can be added to newer issues. =)

This "error" by itself means nothing (which was the error actually?)

And, more than that, this has nothing to do with the solution found to solve this specific issue.

I'm locking this issue so we can concentrate in opened issues.
