### ISSUE TITLE
Invalid syntax in autopep8 submodule, and other errors

### ISSUE THREAD

**Issue by bstiq** [python-mode/python-mode#949]
Hello,

I've been trying for some time to make python-mode work on my machine, to no avail.
I have installed vim huge without GUI with python and python3, python 3.7 and vim-plug, and no other plugins, 

PymodeLintAuto is not working, syntax coloring is not working, and no shortcuts either (run, go to definition...)

Here is my log file:

```
-------------------------------------------------------------------------------
pymode debug msg 1: Starting debug on: 2018-10-12 09:28:20 with file c:\users\qleb\appdata\local\temp\pymode_debug_file.txt
-------------------------------------------------------------------------------
pymode debug msg 2: Operating system: Windows
-------------------------------------------------------------------------------
pymode debug msg 3: Scriptnames:
  1: ~\vimfiles\plugged\python-mode\debugvimrc.vim
  2: C:\Program Files (x86)\Vim\vim81\plugin\getscriptPlugin.vim
  3: C:\Program Files (x86)\Vim\vim81\plugin\gzip.vim
  4: C:\Program Files (x86)\Vim\vim81\plugin\logiPat.vim
  5: C:\Program Files (x86)\Vim\vim81\plugin\manpager.vim
  6: C:\Program Files (x86)\Vim\vim81\plugin\matchparen.vim
  7: C:\Program Files (x86)\Vim\vim81\plugin\netrwPlugin.vim
  8: C:\Program Files (x86)\Vim\vim81\plugin\rrhelper.vim
  9: C:\Program Files (x86)\Vim\vim81\plugin\spellfile.vim
 10: C:\Program Files (x86)\Vim\vim81\plugin\tarPlugin.vim
 11: C:\Program Files (x86)\Vim\vim81\plugin\tohtml.vim
 12: C:\Program Files (x86)\Vim\vim81\plugin\vimballPlugin.vim
 13: C:\Program Files (x86)\Vim\vim81\plugin\zipPlugin.vim
 14: ~\vimfiles\plugged\python-mode\plugin\pymode.vim
 15: ~\vimfiles\plugged\python-mode\autoload\pymode.vim
 16: C:\Program Files (x86)\Vim\vim81\filetype.vim
 17: C:\Program Files (x86)\Vim\vim81\ftplugin.vim
 18: C:\Program Files (x86)\Vim\vim81\ftplugin\python.vim
 19: ~\vimfiles\plugged\python-mode\ftplugin\python\pymode.vim
 20: ~\vimfiles\plugged\python-mode\autoload\pymode\virtualenv.vim
 21: ~\vimfiles\plugged\python-mode\autoload\pymode\breakpoint.vim
 22: ~\vimfiles\plugged\python-mode\autoload\pymode\debug.vim
-------------------------------------------------------------------------------
pymode debug msg 4: Pymode variables:
pymode                #1
pymode_breakpoint     #1
pymode_breakpoint_bind  <leader>b
pymode_breakpoint_cmd  import pdb; pdb.set_trace()  # XXX BREAKPOINT
pymode_debug          #1
pymode_debug_counter  #3
pymode_debug_tempfile  c:\users\qleb\appdata\local\temp\pymode_debug_file.txt
pymode_doc            #1
pymode_doc_bind        K
pymode_doc_vertical   #0
pymode_folding        #0
pymode_folding_nest_limit #1000
pymode_folding_regex   ^\s*\%(class\|def\|async\s\+def\) .\+\(:\s\+\w\)\@!
pymode_indent         #1
pymode_init           #1
pymode_lint           #1
pymode_lint_async     #1
pymode_lint_async_updatetime #1000
pymode_lint_checkers  ['pyflakes', 'pep8', 'mccabe']
pymode_lint_comment_symbol  CC
pymode_lint_cwindow   #1
pymode_lint_docs_symbol  DD
pymode_lint_error_symbol  EE
pymode_lint_ignore    []
pymode_lint_info_symbol  II
pymode_lint_message   #1
pymode_lint_on_fly    #0
pymode_lint_on_write  #1
pymode_lint_options_mccabe {'complexity': 12}
pymode_lint_options_pep257 {}
pymode_lint_options_pep8 {'max_line_length': 79}
pymode_lint_options_pyflakes {'builtins': '_'}
pymode_lint_options_pylint {'max-line-length': 79}
pymode_lint_pyflakes_symbol  FF
pymode_lint_select    []
pymode_lint_signs     #1
pymode_lint_sort      []
pymode_lint_todo_symbol  WW
pymode_lint_unmodified #0
pymode_lint_visual_symbol  RR
pymode_motion         #1
pymode_options        #1
pymode_options_colorcolumn #1
pymode_options_max_line_length #79
pymode_paths          []
pymode_python          python
pymode_quickfix_maxheight #6
pymode_quickfix_minheight #3
pymode_rope           #0
pymode_run            #1
pymode_run_bind        <leader>r
pymode_trim_whitespaces #1
pymode_version         0.9.4
pymode_virtualenv     #1
pymode_virtualenv_enabled  
pymode_virtualenv_path  
pymode_warning        #1
-------------------------------------------------------------------------------
pymode debug msg 5: Git commit: 
Erreur détectée en traitant function pymode#debug#sysinfo :
ligne   33 :
E684: index de Liste hors limites : 0 au-delà de la fin
E116: Arguments invalides pour la fonction substitute( filter( split(l:scriptnames_var, '\n'), 'v:val =~ "/python-mode/"')[0], '\(^\s\+[0-9]\+:\s\+\)\([/~].*python-mode\/\)\(.*\)', '\2', '')
E15: Expression invalide : substitute( filter( split(l:scriptnames_var, '\n'), 'v:val =~ "/python-mode/"')[0], '\(^\s\+[0-9]\+:\s\+\)\([/~].*python-mode\/\)\(.*\)', '\2', '')
ligne   40 :
E121: Variable non définie : l:pymode_folder
E116: Arguments invalides pour la fonction expand(l:pymode_folder). ' rev-parse HEAD ' )
E116: Arguments invalides pour la fonction system('git -C ' . expand(l:pymode_folder). ' rev-parse HEAD ' )
E15: Expression invalide : system('git -C ' . expand(l:pymode_folder). ' rev-parse HEAD ' )
ligne   41 :
E121: Variable non définie : l:git_head_sha1
E116: Arguments invalides pour la fonction split(l:git_head_sha1, '\zs'), 'v:val =~? "[0-9A-Fa-f]"'), '')
E116: Arguments invalides pour la fonction filter(split(l:git_head_sha1, '\zs'), 'v:val =~? "[0-9A-Fa-f]"'), '')
E116: Arguments invalides pour la fonction join(filter(split(l:git_head_sha1, '\zs'), 'v:val =~? "[0-9A-Fa-f]"'), '')
E15: Expression invalide : join(filter(split(l:git_head_sha1, '\zs'), 'v:val =~? "[0-9A-Fa-f]"'), '')
-------------------------------------------------------------------------------
pymode debug msg 6: End of pymode#debug#sysinfo

"pymode.txt" 
"pymode.txt" [lecture-seule] 851L, 32820C





VIM - Vi IMproved 8.1 (2018 May 18, compilé Oct  9 2018 22:07:10)
Version console MS-Windows 64 bits
Rustines incluses : 1-468
Compilé par appveyor@APPVYR-WIN
Énorme version sans interface graphique.  Fonctionnalités incluses (+) ou non (-) :
+acl                +cryptv             +gettext/dyn        -mouseshape         +scrollbind         +user_commands
+arabic             +cscope             -hangul_input       +multi_byte_ime/dyn +signs              +vartabs
+autocmd            +cursorbind         +iconv/dyn          +multi_lang         +smartindent        +vertsplit
+autochdir          +cursorshape        +insert_expand      +mzscheme/dyn       +startuptime        +virtualedit
+autoservername     +dialog_con         +job                -netbeans_intg      +statusline         +visual
-balloon_eval       +diff               +jumplist           +num64              -sun_workshop       +visualextra
+balloon_eval_term  +digraphs           +keymap             +packages           +syntax             +viminfo
-browse             -dnd                +lambda             +path_extra         +tag_binary         +vreplace
++builtin_terms     -ebcdic             +langmap            +perl/dyn           +tag_old_static     +vtp
+byte_offset        +emacs_tags         +libcall            +persistent_undo    -tag_any_white      +wildignore
+channel            +eval               +linebreak          -postscript         +tcl/dyn            +wildmenu
+cindent            +ex_extra           +lispindent         +printer            +termguicolors      +windows
+clientserver       +extra_search       +listcmds           +profile            +terminal           +writebackup
+clipboard          +farsi              +localmap           +python/dyn         -tgetent            -xfontset
+cmdline_compl      +file_in_path       +lua/dyn            +python3/dyn        -termresponse       -xim
+cmdline_hist       +find_in_path       +menu               +quickfix           +textobjects        -xpm_w32
+cmdline_info       +float              +mksession          +reltime            +timers             -xterm_save
+comments           +folding            +modify_fname       +rightleft          +title              
+conceal            -footer             +mouse              +ruby/dyn           -toolbar            
         fichier vimrc système : "$VIM\vimrc"
     fichier vimrc utilisateur : "$HOME\_vimrc"
 2me fichier vimrc utilisateur : "$HOME\vimfiles\vimrc"
 3me fichier vimrc utilisateur : "$VIM\_vimrc"



VIM - Vi IMproved 8.1 (2018 May 18, compilé Oct  9 2018 22:07:10)
Version console MS-Windows 64 bits
Rustines incluses : 1-468
Compilé par appveyor@APPVYR-WIN
Énorme version sans interface graphique.  Fonctionnalités incluses (+) ou non (-) :
+acl                +cryptv             +gettext/dyn        -mouseshape         +scrollbind         +user_commands
+arabic             +cscope             -hangul_input       +multi_byte_ime/dyn +signs              +vartabs
+autocmd            +cursorbind         +iconv/dyn          +multi_lang         +smartindent        +vertsplit
+autochdir          +cursorshape        +insert_expand      +mzscheme/dyn       +startuptime        +virtualedit
+autoservername     +dialog_con         +job                -netbeans_intg      +statusline         +visual
-balloon_eval       +diff               +jumplist           +num64              -sun_workshop       +visualextra
+balloon_eval_term  +digraphs           +keymap             +packages           +syntax             +viminfo
-browse             -dnd                +lambda             +path_extra         +tag_binary         +vreplace
++builtin_terms     -ebcdic             +langmap            +perl/dyn           +tag_old_static     +vtp
+byte_offset        +emacs_tags         +libcall            +persistent_undo    -tag_any_white      +wildignore
+channel            +eval               +linebreak          -postscript         +tcl/dyn            +wildmenu
+cindent            +ex_extra           +lispindent         +printer            +termguicolors      +windows
+clientserver       +extra_search       +listcmds           +profile            +terminal           +writebackup
+clipboard          +farsi              +localmap           +python/dyn         -tgetent            -xfontset
+cmdline_compl      +file_in_path       +lua/dyn            +python3/dyn        -termresponse       -xim
+cmdline_hist       +find_in_path       +menu               +quickfix           +textobjects        -xpm_w32
+cmdline_info       +float              +mksession          +reltime            +timers             -xterm_save
+comments           +folding            +modify_fname       +rightleft          +title              
+conceal            -footer             +mouse              +ruby/dyn           -toolbar            
         fichier vimrc système : "$VIM\vimrc"
     fichier vimrc utilisateur : "$HOME\_vimrc"
 2me fichier vimrc utilisateur : "$HOME\vimfiles\vimrc"
 3me fichier vimrc utilisateur : "$VIM\_vimrc"


1

1
  1  
-------------------------------------------------------------------------------
pymode debug msg 7: Session history:
      #  cmd history
      1  cd Documents\cmeo\trunk\Outils_Python\automatisation-tickets\
      2  e configReader.py
      3  help pymode
      5  q
      7  version
      8  echo has('python')
>     9  echo has('python3')
Exception KeyError: KeyError(8976,) in <module 'threading' from 'C:\Python27\Lib\threading.pyc'> ignored
-------------------------------------------------------------------------------
pymode debug msg 1: Starting debug on: 2018-10-12 09:33:10 with file c:\users\qleb\appdata\local\temp\pymode_debug_file.txt
-------------------------------------------------------------------------------
pymode debug msg 2: Operating system: Windows
-------------------------------------------------------------------------------
pymode debug msg 3: Scriptnames:
  1: ~\vimfiles\plugged\python-mode\debugvimrc.vim
  2: C:\Program Files (x86)\Vim\vim81\plugin\getscriptPlugin.vim
  3: C:\Program Files (x86)\Vim\vim81\plugin\gzip.vim
  4: C:\Program Files (x86)\Vim\vim81\plugin\logiPat.vim
  5: C:\Program Files (x86)\Vim\vim81\plugin\manpager.vim
  6: C:\Program Files (x86)\Vim\vim81\plugin\matchparen.vim
  7: C:\Program Files (x86)\Vim\vim81\plugin\netrwPlugin.vim
  8: C:\Program Files (x86)\Vim\vim81\plugin\rrhelper.vim
  9: C:\Program Files (x86)\Vim\vim81\plugin\spellfile.vim
 10: C:\Program Files (x86)\Vim\vim81\plugin\tarPlugin.vim
 11: C:\Program Files (x86)\Vim\vim81\plugin\tohtml.vim
 12: C:\Program Files (x86)\Vim\vim81\plugin\vimballPlugin.vim
 13: C:\Program Files (x86)\Vim\vim81\plugin\zipPlugin.vim
 14: ~\vimfiles\plugged\python-mode\plugin\pymode.vim
 15: ~\vimfiles\plugged\python-mode\autoload\pymode.vim
 16: C:\Program Files (x86)\Vim\vim81\filetype.vim
 17: C:\Program Files (x86)\Vim\vim81\ftplugin.vim
 18: C:\Program Files (x86)\Vim\vim81\scripts.vim
 19: C:\Program Files (x86)\Vim\vim81\ftplugin\python.vim
 20: ~\vimfiles\plugged\python-mode\ftplugin\python\pymode.vim
 21: ~\vimfiles\plugged\python-mode\autoload\pymode\virtualenv.vim
 22: ~\vimfiles\plugged\python-mode\autoload\pymode\breakpoint.vim
 23: ~\vimfiles\plugged\python-mode\autoload\pymode\debug.vim
-------------------------------------------------------------------------------
pymode debug msg 4: Pymode variables:
pymode                #1
pymode_breakpoint     #1
pymode_breakpoint_bind  <leader>b
pymode_breakpoint_cmd  import pdb; pdb.set_trace()  # XXX BREAKPOINT
pymode_debug          #1
pymode_debug_counter  #3
pymode_debug_tempfile  c:\users\qleb\appdata\local\temp\pymode_debug_file.txt
pymode_doc            #1
pymode_doc_bind        K
pymode_doc_vertical   #0
pymode_folding        #0
pymode_folding_nest_limit #1000
pymode_folding_regex   ^\s*\%(class\|def\|async\s\+def\) .\+\(:\s\+\w\)\@!
pymode_indent         #1
pymode_init           #1
pymode_lint           #1
pymode_lint_async     #1
pymode_lint_async_updatetime #1000
pymode_lint_checkers  ['pyflakes', 'pep8', 'mccabe']
pymode_lint_comment_symbol  CC
pymode_lint_cwindow   #1
pymode_lint_docs_symbol  DD
pymode_lint_error_symbol  EE
pymode_lint_ignore    []
pymode_lint_info_symbol  II
pymode_lint_message   #1
pymode_lint_on_fly    #0
pymode_lint_on_write  #1
pymode_lint_options_mccabe {'complexity': 12}
pymode_lint_options_pep257 {}
pymode_lint_options_pep8 {'max_line_length': 79}
pymode_lint_options_pyflakes {'builtins': '_'}
pymode_lint_options_pylint {'max-line-length': 79}
pymode_lint_pyflakes_symbol  FF
pymode_lint_select    []
pymode_lint_signs     #1
pymode_lint_sort      []
pymode_lint_todo_symbol  WW
pymode_lint_unmodified #0
pymode_lint_visual_symbol  RR
pymode_motion         #1
pymode_options        #1
pymode_options_colorcolumn #1
pymode_options_max_line_length #79
pymode_paths          []
pymode_python          python
pymode_quickfix_maxheight #6
pymode_quickfix_minheight #3
pymode_rope           #0
pymode_run            #1
pymode_run_bind        <leader>r
pymode_trim_whitespaces #1
pymode_version         0.9.4
pymode_virtualenv     #1
pymode_virtualenv_enabled  
pymode_virtualenv_path  
pymode_warning        #1
-------------------------------------------------------------------------------
pymode debug msg 5: Git commit: 
Erreur détectée en traitant function pymode#debug#sysinfo :
ligne   33 :
E684: index de Liste hors limites : 0 au-delà de la fin
E116: Arguments invalides pour la fonction substitute( filter( split(l:scriptnames_var, '\n'), 'v:val =~ "/python-mode/"')[0], '\(^\s\+[0-9]\+:\s\+\)\([/~].*python-mode\/\)\(.*\)', '\2', '')
E15: Expression invalide : substitute( filter( split(l:scriptnames_var, '\n'), 'v:val =~ "/python-mode/"')[0], '\(^\s\+[0-9]\+:\s\+\)\([/~].*python-mode\/\)\(.*\)', '\2', '')
ligne   40 :
E121: Variable non définie : l:pymode_folder
E116: Arguments invalides pour la fonction expand(l:pymode_folder). ' rev-parse HEAD ' )
E116: Arguments invalides pour la fonction system('git -C ' . expand(l:pymode_folder). ' rev-parse HEAD ' )
E15: Expression invalide : system('git -C ' . expand(l:pymode_folder). ' rev-parse HEAD ' )
ligne   41 :
E121: Variable non définie : l:git_head_sha1
E116: Arguments invalides pour la fonction split(l:git_head_sha1, '\zs'), 'v:val =~? "[0-9A-Fa-f]"'), '')
E116: Arguments invalides pour la fonction filter(split(l:git_head_sha1, '\zs'), 'v:val =~? "[0-9A-Fa-f]"'), '')
E116: Arguments invalides pour la fonction join(filter(split(l:git_head_sha1, '\zs'), 'v:val =~? "[0-9A-Fa-f]"'), '')
E15: Expression invalide : join(filter(split(l:git_head_sha1, '\zs'), 'v:val =~? "[0-9A-Fa-f]"'), '')
-------------------------------------------------------------------------------
pymode debug msg 6: End of pymode#debug#sysinfo

E492: Commande inconnue: pymode

Maintenance des messages : Dominique Pellé <dominique.pelle@gmail.com>
C:\Users\QLEB\Documents\cmeo\trunk\Outils_Python\automatisation-tickets
"infoReader.py" 9L, 368C
-------------------------------------------------------------------------------
pymode debug msg 1: Starting debug on: 2018-10-12 09:33:10 with file c:\users\qleb\appdata\local\temp\pymode_debug_file.txt
-------------------------------------------------------------------------------
pymode debug msg 2: Operating system: Windows
-------------------------------------------------------------------------------
pymode debug msg 3: Scriptnames:
-------------------------------------------------------------------------------
pymode debug msg 4: Pymode variables:
pymode                #1
pymode_breakpoint     #1
pymode_breakpoint_bind  <leader>b
pymode_breakpoint_cmd  import pdb; pdb.set_trace()  # XXX BREAKPOINT
pymode_debug          #1
pymode_debug_counter  #3
pymode_debug_tempfile  c:\users\qleb\appdata\local\temp\pymode_debug_file.txt
pymode_doc            #1
pymode_doc_bind        K
pymode_doc_vertical   #0
pymode_folding        #0
pymode_folding_nest_limit #1000
pymode_folding_regex   ^\s*\%(class\|def\|async\s\+def\) .\+\(:\s\+\w\)\@!
pymode_indent         #1
pymode_init           #1
pymode_lint           #1
pymode_lint_async     #1
pymode_lint_async_updatetime #1000
pymode_lint_checkers  ['pyflakes', 'pep8', 'mccabe']
pymode_lint_comment_symbol  CC
pymode_lint_cwindow   #1
pymode_lint_docs_symbol  DD
pymode_lint_error_symbol  EE
pymode_lint_ignore    []
pymode_lint_info_symbol  II
pymode_lint_message   #1
pymode_lint_on_fly    #0
pymode_lint_on_write  #1
pymode_lint_options_mccabe {'complexity': 12}
pymode_lint_options_pep257 {}
pymode_lint_options_pep8 {'max_line_length': 79}
pymode_lint_options_pyflakes {'builtins': '_'}
pymode_lint_options_pylint {'max-line-length': 79}
pymode_lint_pyflakes_symbol  FF
pymode_lint_select    []
pymode_lint_signs     #1
pymode_lint_sort      []
pymode_lint_todo_symbol  WW
pymode_lint_unmodified #0
pymode_lint_visual_symbol  RR
pymode_motion         #1
pymode_options        #1
pymode_options_colorcolumn #1
pymode_options_max_line_length #79
pymode_paths          []
pymode_python          python
pymode_quickfix_maxheight #6
pymode_quickfix_minheight #3
pymode_rope           #0
pymode_run            #1
pymode_run_bind        <leader>r
pymode_trim_whitespaces #1
pymode_version         0.9.4
pymode_virtualenv     #1
pymode_virtualenv_enabled  
pymode_virtualenv_path  
pymode_warning        #1
-------------------------------------------------------------------------------
pymode debug msg 5: Git commit: 
Erreur détectée en traitant function pymode#debug#sysinfo :
ligne   33 :
E684: index de Liste hors limites : 0 au-delà de la fin
E116: Arguments invalides pour la fonction substitute( filter( split(l:scriptnames_var, '\n'), 'v:val =~ "/python-mode/"')[0], '\(^\s\+[0-9]\+:\s\+\)\([/~].*python-mode\/\)\(.*\)', '\2', '')
E15: Expression invalide : substitute( filter( split(l:scriptnames_var, '\n'), 'v:val =~ "/python-mode/"')[0], '\(^\s\+[0-9]\+:\s\+\)\([/~].*python-mode\/\)\(.*\)', '\2', '')
ligne   40 :
E121: Variable non définie : l:pymode_folder
E116: Arguments invalides pour la fonction expand(l:pymode_folder). ' rev-parse HEAD ' )
E116: Arguments invalides pour la fonction system('git -C ' . expand(l:pymode_folder). ' rev-parse HEAD ' )
E15: Expression invalide : system('git -C ' . expand(l:pymode_folder). ' rev-parse HEAD ' )
ligne   41 :
E121: Variable non définie : l:git_head_sha1
E116: Arguments invalides pour la fonction split(l:git_head_sha1, '\zs'), 'v:val =~? "[0-9A-Fa-f]"'), '')
E116: Arguments invalides pour la fonction filter(split(l:git_head_sha1, '\zs'), 'v:val =~? "[0-9A-Fa-f]"'), '')
E116: Arguments invalides pour la fonction join(filter(split(l:git_head_sha1, '\zs'), 'v:val =~? "[0-9A-Fa-f]"'), '')
E15: Expression invalide : join(filter(split(l:git_head_sha1, '\zs'), 'v:val =~? "[0-9A-Fa-f]"'), '')
-------------------------------------------------------------------------------
pymode debug msg 6: End of pymode#debug#sysinfo
E492: Commande inconnue: pymode

"pymode.txt" 
"pymode.txt" [lecture-seule] 851L, 32820C

E474: Argument invalide: encoding='utf-8'

E21: Impossible de modifier, 'modifiable' est dÃ©sactivÃ©




Maintenance des messages : Dominique PellÃ© <dominique.pelle@gmail.com>
C:\Users\QLEB\Documents\cmeo\trunk\Outils_Python\automatisation-tickets
"infoReader.py" 9L, 368C
-------------------------------------------------------------------------------
pymode debug msg 1: Starting debug on: 2018-10-12 09:33:10 with file c:\users\qleb\appdata\local\temp\pymode_debug_file.txt
-------------------------------------------------------------------------------
pymode debug msg 2: Operating system: Windows
-------------------------------------------------------------------------------
pymode debug msg 3: Scriptnames:
-------------------------------------------------------------------------------
pymode debug msg 4: Pymode variables:
pymode                #1
pymode_breakpoint     #1
pymode_breakpoint_bind  <leader>b
pymode_breakpoint_cmd  import pdb; pdb.set_trace()  # XXX BREAKPOINT
pymode_debug          #1
pymode_debug_counter  #3
pymode_debug_tempfile  c:\users\qleb\appdata\local\temp\pymode_debug_file.txt
pymode_doc            #1
pymode_doc_bind        K
pymode_doc_vertical   #0
pymode_folding        #0
pymode_folding_nest_limit #1000
pymode_folding_regex   ^\s*\%(class\|def\|async\s\+def\) .\+\(:\s\+\w\)\@!
pymode_indent         #1
pymode_init           #1
pymode_lint           #1
pymode_lint_async     #1
pymode_lint_async_updatetime #1000
pymode_lint_checkers  ['pyflakes', 'pep8', 'mccabe']
pymode_lint_comment_symbol  CC
pymode_lint_cwindow   #1
pymode_lint_docs_symbol  DD
pymode_lint_error_symbol  EE
pymode_lint_ignore    []
pymode_lint_info_symbol  II
pymode_lint_message   #1
pymode_lint_on_fly    #0
pymode_lint_on_write  #1
pymode_lint_options_mccabe {'complexity': 12}
pymode_lint_options_pep257 {}
pymode_lint_options_pep8 {'max_line_length': 79}
pymode_lint_options_pyflakes {'builtins': '_'}
pymode_lint_options_pylint {'max-line-length': 79}
pymode_lint_pyflakes_symbol  FF
pymode_lint_select    []
pymode_lint_signs     #1
pymode_lint_sort      []
pymode_lint_todo_symbol  WW
pymode_lint_unmodified #0
pymode_lint_visual_symbol  RR
pymode_motion         #1
pymode_options        #1
pymode_options_colorcolumn #1
pymode_options_max_line_length #79
pymode_paths          []
pymode_python          python
pymode_quickfix_maxheight #6
pymode_quickfix_minheight #3
pymode_rope           #0
1 modification ; avant #1 ; il y a 1 seconde
1 modification ; avant #1 ; il y a 1 seconde

[Pymode] Code checking is running ...
1539329952 ['pyflakes', 'pep8', 'mccabe'] []
1539329952 Namespace(abspath=False, concurrent=False, file_params={}, force=True, format='pycodestyle', hook=False, ignore=[], linters=[('pyflakes', <pylama.lint.pylama_pyflakes.Linter object at 0x0000020E95DE1898>), ('pep8', <pylama.lint.pylama_pycodestyle.Linter object at 0x0000020E95C58048>), ('mccabe', <pylama.lint.pylama_mccabe.Linter object at 0x0000020E95BA2240>)], linters_params={}, options=None, paths=['C:\\Users\\QLEB\\Documents\\cmeo\\trunk\\Outils_Python\\automatisation-tickets'], report=None, select=[], skip=[], sort=[], verbose=False) []
1539329952 Start code check:  [infoReader.py]
Checking params: {'ignore': set([]), 'skip': False, 'linters': [], 'select': set([])}
Run pyflakes {'builtins': '_'}
Run pep8 {'max_line_length': '79'}
Run mccabe {'complexity': '12'}
1539329952 Find errors:  [0]
[Pymode] Code checking is completed. No errors found.

Erreur dÃ©tectÃ©e en traitant function pymode#lint#auto :
ligne    5 :
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\QLEB\vimfiles\plugged\python-mode\pymode\__init__.py", line 15, in auto
    from .autopep8 import fix_file
  File "C:\Users\QLEB\vimfiles\plugged\python-mode\pymode\autopep8.py", line 1
    ../submodules/autopep8/autopep8.py
    ^
SyntaxError: invalid syntax
"infoReader.py" 
"infoReader.py" 9L, 368C
[Pymode] AutoPep8 done.

Maintenance des messages : Dominique PellÃ© <dominique.pelle@gmail.com>
C:\Users\QLEB\Documents\cmeo\trunk\Outils_Python\automatisation-tickets
"infoReader.py" 9L, 368C
-------------------------------------------------------------------------------
pymode debug msg 1: Starting debug on: 2018-10-12 09:33:10 with file c:\users\qleb\appdata\local\temp\pymode_debug_file.txt
-------------------------------------------------------------------------------
pymode debug msg 2: Operating system: Windows
-------------------------------------------------------------------------------
pymode debug msg 3: Scriptnames:
-------------------------------------------------------------------------------
pymode debug msg 4: Pymode variables:
pymode                #1
pymode_breakpoint     #1
pymode_breakpoint_bind  <leader>b
pymode_breakpoint_cmd  import pdb; pdb.set_trace()  # XXX BREAKPOINT
pymode_debug          #1
pymode_debug_counter  #3
pymode_debug_tempfile  c:\users\qleb\appdata\local\temp\pymode_debug_file.txt
pymode_doc            #1
pymode_doc_bind        K
pymode_doc_vertical   #0
pymode_folding        #0
pymode_folding_nest_limit #1000
pymode_folding_regex   ^\s*\%(class\|def\|async\s\+def\) .\+\(:\s\+\w\)\@!
pymode_indent         #1
pymode_init           #1
pymode_lint           #1
pymode_lint_async     #1
pymode_lint_async_updatetime #1000
pymode_lint_checkers  ['pyflakes', 'pep8', 'mccabe']
pymode_lint_comment_symbol  CC
pymode_lint_cwindow   #1
pymode_lint_docs_symbol  DD
pymode_lint_error_symbol  EE
pymode_lint_ignore    []
pymode_lint_info_symbol  II
pymode_lint_message   #1
pymode_lint_on_fly    #0
pymode_lint_on_write  #1
pymode_lint_options_mccabe {'complexity': 12}
pymode_lint_options_pep257 {}
pymode_lint_options_pep8 {'max_line_length': 79}
pymode_lint_options_pyflakes {'builtins': '_'}
pymode_lint_options_pylint {'max-line-length': 79}
pymode_lint_pyflakes_symbol  FF
pymode_lint_select    []
pymode_lint_signs     #1
pymode_lint_sort      []
pymode_lint_todo_symbol  WW
pymode_lint_unmodified #0
pymode_lint_visual_symbol  RR
pymode_motion         #1
pymode_options        #1
pymode_options_colorcolumn #1
pymode_options_max_line_length #79
pymode_paths          []
pymode_python          python
pymode_quickfix_maxheight #6
pymode_quickfix_minheight #3
pymode_rope           #0
pymode_run            #1
pymode_run_bind        <leader>r
pymode_trim_whitespaces #1
pymode_version         0.9.4
pymode_virtualenv     #1
pymode_virtualenv_enabled  
pymode_virtualenv_path  
pymode_warning        #1
-------------------------------------------------------------------------------
pymode debug msg 5: Git commit: 
Erreur d<e9>tect<e9>e en traitant function pymode#debug#sysinfo :
ligne   33 :
E684: index de Liste hors limites : 0 au-del<e0> de la fin
E116: Arguments invalides pour la fonction substitute( filter( split(l:scriptnames_var, '\n'), 'v:val =~ "/python-mode/"')[0], '\(^\s\+[0-9]\+:\s\+\)\([/~].*python-mode\/\)\(.*\)', '\2', '')
E15: Expression invalide : substitute( filter( split(l:scriptnames_var, '\n'), 'v:val =~ "/python-mode/"')[0], '\(^\s\+[0-9]\+:\s\+\)\([/~].*python-mode\/\)\(.*\)', '\2', '')
ligne   40 :
E121: Variable non d<e9>finie : l:pymode_folder
E116: Arguments invalides pour la fonction expand(l:pymode_folder). ' rev-parse HEAD ' )
E116: Arguments invalides pour la fonction system('git -C ' . expand(l:pymode_folder). ' rev-parse HEAD ' )
E15: Expression invalide : system('git -C ' . expand(l:pymode_folder). ' rev-parse HEAD ' )
ligne   41 :
E121: Variable non d<e9>finie : l:git_head_sha1
E116: Arguments invalides pour la fonction split(l:git_head_sha1, '\zs'), 'v:val =~? "[0-9A-Fa-f]"'), '')
E116: Arguments invalides pour la fonction filter(split(l:git_head_sha1, '\zs'), 'v:val =~? "[0-9A-Fa-f]"'), '')
E116: Arguments invalides pour la fonction join(filter(split(l:git_head_sha1, '\zs'), 'v:val =~? "[0-9A-Fa-f]"'), '')
E15: Expression invalide : join(filter(split(l:git_head_sha1, '\zs'), 'v:val =~? "[0-9A-Fa-f]"'), '')
-------------------------------------------------------------------------------
pymode debug msg 6: End of pymode#debug#sysinfo
E492: Commande inconnue: pymode
"pymode.txt" [lecture-seule] 851L, 32820C
E474: Argument invalide: encoding='utf-8'
E21: Impossible de modifier, 'modifiable' est dÃ©sactivÃ©


1 modification ; avant #1 ; il y a 1 seconde
1539329952 ['pyflakes', 'pep8', 'mccabe'] []
1539329952 Namespace(abspath=False, concurrent=False, file_params={}, force=True, format='pycodestyle', hook=False, ignore=[], linters=[('pyflakes', <pylama.lint.pylama_pyflakes.Linter object at 0x0000020E95DE1898>), ('pep8', <pylama.lint.pylama_pycodestyle.Linter object at 0x0000020E95C58048>), ('mccabe
```

Sorry, some text is in french...

Does anyone know what is happening ?

Thanks

**Comment by diraol** [comment]
Hi @lebastaq this is related to the issue #978. You can find you answer there. =)

I'll close this issue (since the solution to the problem is in #978). If it does not work, feel free to reopen this issue ok?

(I'm sorry taking so long to answer, I've become maintainer of the project no that long ago and I'm trying to take a look at old issues that still open)
