### ISSUE TITLE
AttributeError: module 'vim' has no attribute 'find_spec'

### ISSUE THREAD

**Issue by seashaw** [python-mode/python-mode#958]
Hello, there seems to be similar issues that might be related to this, but latest develop commit is still not working.
I tried compiling and using latest vim from git repo. Reverted to version from Ubuntu repo when it made no difference. Also tried re-installing python-mode via vim-plug and also did not help.

Not sure what I can try next, if anyone has encountered this on system similar to mine (Ubuntu 18.10) please share any workarounds.

:messages
-----------
```
Error detected while processing <snip>/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Error detected while processing <snip>/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing <snip>/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<snip>/.vim/plugged/python-mode/pymode/lint.py", line 9, in <module>
Error detected while processing <snip>/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Error detected while processing <snip>/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<snip>/.vim/plugged/python-mode/pymode/libs/pylama/lint/extensions.py", line 44, in <module>
Error detected while processing <snip>/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    from pkg_resources import iter_entry_points
Error detected while processing <snip>/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<snip>/.vim/plugged/python-mode/pymode/libs/pkg_resources/__init__.py", line 3092, in <module>
Error detected while processing <snip>/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    @_call_aside
Error detected while processing <snip>/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<snip>/.vim/plugged/python-mode/pymode/libs/pkg_resources/__init__.py", line 3078, in _call_aside
Error detected while processing <snip>/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    f(*args, **kwargs)
Error detected while processing <snip>/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<snip>/.vim/plugged/python-mode/pymode/libs/pkg_resources/__init__.py", line 3117, in _initialize_master_working_set
Error detected while processing <snip>/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    add_activation_listener(lambda dist: dist.activate())
Error detected while processing <snip>/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<snip>/.vim/plugged/python-mode/pymode/libs/pkg_resources/__init__.py", line 965, in subscribe
Error detected while processing <snip>/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    callback(dist)
Error detected while processing <snip>/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<snip>/.vim/plugged/python-mode/pymode/libs/pkg_resources/__init__.py", line 3117, in <lambda>
Error detected while processing <snip>/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    add_activation_listener(lambda dist: dist.activate())
Error detected while processing <snip>/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<snip>/.vim/plugged/python-mode/pymode/libs/pkg_resources/__init__.py", line 2636, in activate
Error detected while processing <snip>/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    declare_namespace(pkg)
Error detected while processing <snip>/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<snip>/.vim/plugged/python-mode/pymode/libs/pkg_resources/__init__.py", line 2227, in declare_namespace
Error detected while processing <snip>/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    _handle_ns(packageName, path_item)
Error detected while processing <snip>/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<snip>/.vim/plugged/python-mode/pymode/libs/pkg_resources/__init__.py", line 2173, in _handle_ns
Error detected while processing <snip>/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    loader = importer.find_spec(packageName)
Error detected while processing <snip>/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
AttributeError: module 'vim' has no attribute 'find_spec'
```

vim --version
---------------
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 05 2018 21:42:14)
Included patches: 1-1766
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               -perl              +vertsplit
-clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           -python            +vreplace
+conceal           +linebreak         +python3           +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       -lua               -ruby              -X11
+dialog_con        +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             -xim
+digraphs          +modify_fname      +smartindent       -xpm
-dnd               +mouse             +startuptime       -xsmp
-ebcdic            -mouseshape        +statusline        -xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              +mouse_gpm         +syntax
+ex_extra          -mouse_jsbterm     +tag_binary
+extra_search      +mouse_netterm     +tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-SKXyA9/vim-8.0.1766=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl     -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lm
```

python3 --version
--------------------
```
Python 3.6.7
```

**Comment by joergsch** [comment]
workaround (which seems to work for me, but this reverts part of pull request #950):
in python-mode/pymode/libs/pkg_resources/\_\_init\_\_.py
line 2173
replace
`loader = importer.find_spec(packageName)`
with
`loader = importer.find_module(packageName)`

**Comment by maufia** [comment]
I have the same issue... **joergsch** suggestion does not help...

## :message
```line 0: sourcing "<hide>/vimrc/.dein/autoload/pymode/lint.vim"
line 0: sourcing "<hide>/vimrc/.dein/autoload/pymode/lint.vim"
Error detected while processing <hide>/vimrc/.dein/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Error detected while processing <hide>/vimrc/.dein/autoload/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing <hide>/vimrc/.dein/autoload/pymode/lint.vim:
line    1:
  File "<hide>/vimrc/.dein/pymode/lint.py", line 9, in <module>
Error detected while processing <hide>/vimrc/.dein/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Error detected while processing <hide>/vimrc/.dein/autoload/pymode/lint.vim:
line    1:
  File "<hide>/vimrc/.dein/pymode/libs/pylama/lint/extensions.py", line 44, in <module>
Error detected while processing <hide>/vimrc/.dein/autoload/pymode/lint.vim:
line    1:
    from pkg_resources import iter_entry_points
Error detected while processing <hide>/vimrc/.dein/autoload/pymode/lint.vim:
line    1:
  File "<hide>/vimrc/.dein/pymode/libs/pkg_resources/__init__.py", line 3092, in <module>
Error detected while processing <hide>/vimrc/.dein/autoload/pymode/lint.vim:
line    1:
    @_call_aside
Error detected while processing <hide>/vimrc/.dein/autoload/pymode/lint.vim:
line    1:
  File "<hide>/vimrc/.dein/pymode/libs/pkg_resources/__init__.py", line 3078, in _call_aside
Error detected while processing <hide>/vimrc/.dein/autoload/pymode/lint.vim:
line    1:
    f(*args, **kwargs)
Error detected while processing <hide>/vimrc/.dein/autoload/pymode/lint.vim:
line    1:
  File "<hide>/vimrc/.dein/pymode/libs/pkg_resources/__init__.py", line 3117, in _initialize_master_working_set
Error detected while processing <hide>/vimrc/.dein/autoload/pymode/lint.vim:
line    1:
    add_activation_listener(lambda dist: dist.activate())
Error detected while processing <hide>/vimrc/.dein/autoload/pymode/lint.vim:
line    1:
  File "<hide>/vimrc/.dein/pymode/libs/pkg_resources/__init__.py", line 965, in subscribe
Error detected while processing <hide>/vimrc/.dein/autoload/pymode/lint.vim:
line    1:
    callback(dist)
Error detected while processing <hide>/vimrc/.dein/autoload/pymode/lint.vim:
line    1:
  File "<hide>/vimrc/.dein/pymode/libs/pkg_resources/__init__.py", line 3117, in <lambda>
Error detected while processing <hide>/vimrc/.dein/autoload/pymode/lint.vim:
line    1:
    add_activation_listener(lambda dist: dist.activate())
Error detected while processing <hide>/vimrc/.dein/autoload/pymode/lint.vim:
line    1:
  File "<hide>/vimrc/.dein/pymode/libs/pkg_resources/__init__.py", line 2636, in activate
Error detected while processing <hide>/vimrc/.dein/autoload/pymode/lint.vim:
line    1:
    declare_namespace(pkg)
Error detected while processing <hide>/vimrc/.dein/autoload/pymode/lint.vim:
line    1:
  File "<hide>/vimrc/.dein/pymode/libs/pkg_resources/__init__.py", line 2227, in declare_namespace
Error detected while processing <hide>/vimrc/.dein/autoload/pymode/lint.vim:
line    1:
    _handle_ns(packageName, path_item)
Error detected while processing <hide>/vimrc/.dein/autoload/pymode/lint.vim:
line    1:
  File "<hide>/vimrc/.dein/pymode/libs/pkg_resources/__init__.py", line 2173, in _handle_ns
Error detected while processing <hide>/vimrc/.dein/autoload/pymode/lint.vim:
line    1:
    loader = importer.find_spec(packageName)
Error detected while processing <hide>/vimrc/.dein/autoload/pymode/lint.vim:
line    1:
AttributeError: module 'vim' has no attribute 'find_spec'
```

## vim version
```VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 30 2017 18:21:38)
Included patches: 1-197, 322, 377-378, 550, 703, 706-707
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     +tcl
+balloon_eval    +folding         +mouse_xterm     +termguicolors
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
+clientserver    +insert_expand   +packages        +toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua             +rightleft       +writebackup
+diff            +menu            +ruby            +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     +xpm
+emacs_tags      +mouseshape      +startuptime     +xsmp_interact
+eval            +mouse_dec       +statusline      +xterm_clipboard
+ex_extra        +mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-R2d1UQ/vim-8.0.0197=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.24/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm
```

## python version
`Python 3.5.3`

**Comment by diraol** [comment]
Fellows, are you facing this problem when opening any kind of files? Any python files? Can you give an example on how to reproduce the error, please?

**Comment by diraol** [comment]
Sorry, closed by mistake

**Comment by diraol** [comment]
Btw, can you please provide me this?

https://github.com/python-mode/python-mode#troubleshootingdebugging

And, if possible, also try opening a python file following the troubleshooting guideline and do something, like running `:PymodeLintAuto`

**Comment by amirgi73** [comment]
Hi
I'm having the same issue...
### vim version:
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 05 2018 21:42:14)
Included patches: 1-1766
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               -perl              +vertsplit
-clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           -python            +vreplace
+conceal           +linebreak         +python3           +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       -lua               -ruby              -X11
+dialog_con        +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             -xim
+digraphs          +modify_fname      +smartindent       -xpm
-dnd               +mouse             +startuptime       -xsmp
-ebcdic            -mouseshape        +statusline        -xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              +mouse_gpm         +syntax            
+ex_extra          -mouse_jsbterm     +tag_binary        
+extra_search      +mouse_netterm     +tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-SKXyA9/vim-8.0.1766=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl     -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lm
```
### Python Version:
Python2: 2.7.15+
Python3: 3.6.7

### steps to reproduce the error:
1. opening any py file
OR
2. creating a new py file:
vim new.py

**debug file attached**
[pymode_debug_file.txt](https://github.com/python-mode/python-mode/files/2588466/pymode_debug_file.txt)

**Comment by nithale** [comment]
Hi,
The same issue is bothering me opening or creating a .py file
debug file ahead attached
[pymode_debug_file.txt](https://github.com/python-mode/python-mode/files/2591250/pymode_debug_file.txt)

**Comment by seashaw** [comment]
@diraol thanks for following up on this.

Here is the debug log:
[pymode_debug_file.txt](https://github.com/python-mode/python-mode/files/2591472/pymode_debug_file.txt)

It happens when trying to open *.py files for editing, even empty files.

When saving a file with obvious pep8 errors it show 'Code checking is completed. No errors found.'

However :PymodeLintAuto seems to work as it should, fixing formatting issues in the file.

**Comment by seashaw** [comment]
The workaround posted by @joergsch seems to work for me, worth a try if anyone else is experiencing this issue.

**Comment by lethargi** [comment]
The workaround by @joergsch fixes the code checking and Python-mode error messages for me too

**Comment by jia3ep** [comment]
The workaround by @joergsch fixes error messages, but additionally it was needed to add the following line in .vimrc:
`let g:pymode_python = 'python3'`
and run the following command then:
`find ~/.vim -name \*.pyc -delete`
