### ISSUE TITLE
AttributeError: 'zipimport.zipimporter' object has no attribute 'find_spec'

### ISSUE THREAD

**Issue by fxdgear** [python-mode/python-mode#960]
Running Neovim, using dein package manager I've manually gone to the location where python_mode is installed and updated all the git submodules

ive tried telling neovim to use python 3.6 as opposed to python 3.7 but still getting this error. 

```-------------------------------------------------------------------------------
pymode debug msg 1: Starting debug on: 2018-11-14 12:48:00 with file /tmp/pymode_debug_file.txt
-------------------------------------------------------------------------------
pymode debug msg 2: Operating system: Linux
-------------------------------------------------------------------------------
pymode debug msg 3: Scriptnames:
  1: ~/.cache/dein/repos/github.com/python-mode/python-mode/debugvimrc.vim
  2: /usr/share/vim/vim81/plugin/getscriptPlugin.vim
  3: /usr/share/vim/vim81/plugin/gzip.vim
  4: /usr/share/vim/vim81/plugin/logiPat.vim
  5: /usr/share/vim/vim81/plugin/manpager.vim
  6: /usr/share/vim/vim81/plugin/matchparen.vim
  7: /usr/share/vim/vim81/plugin/netrwPlugin.vim
  8: /usr/share/vim/vim81/plugin/rrhelper.vim
  9: /usr/share/vim/vim81/plugin/spellfile.vim
 10: /usr/share/vim/vim81/plugin/tarPlugin.vim
 11: /usr/share/vim/vim81/plugin/tohtml.vim
 12: /usr/share/vim/vim81/plugin/vimballPlugin.vim
 13: /usr/share/vim/vim81/plugin/zipPlugin.vim
 14: ~/.cache/dein/repos/github.com/python-mode/python-mode/plugin/pymode.vim
 15: ~/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode.vim
 16: /usr/share/vim/vim81/filetype.vim
 17: /usr/share/vim/vimfiles/ftdetect/PKGBUILD.vim
 18: /usr/share/vim/vimfiles/ftdetect/dockerfile.vim
 19: /usr/share/vim/vimfiles/ftdetect/meson.vim
 20: /usr/share/vim/vimfiles/ftdetect/vagrantfile.vim
 21: /usr/share/vim/vim81/ftplugin.vim
 22: /usr/share/vim/vim81/ftplugin/python.vim
 23: ~/.cache/dein/repos/github.com/python-mode/python-mode/ftplugin/python/pymode.vim
 24: ~/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/virtualenv.vim
 25: ~/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/breakpoint.vim
 26: ~/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/debug.vim
-------------------------------------------------------------------------------
pymode debug msg 4: Pymode variables:
pymode                #1
pymode_breakpoint     #1
pymode_breakpoint_bind  <leader>b
pymode_breakpoint_cmd  import ipdb; ipdb.set_trace()  # XXX BREAKPOINT
pymode_debug          #1
pymode_debug_counter  #3
pymode_debug_tempfile  /tmp/pymode_debug_file.txt
pymode_doc            #1
pymode_doc_bind        K
pymode_doc_vertical   #0
pymode_folding        #0
pymode_folding_nest_limit #1000
pymode_folding_regex   ^\s*\%(class\|def\|async\s\+def\) .\+\(:\s\+\w\)\@!
pymode_indent         #1
pymode_init           #1
pymode_lint           #1
pymode_lint_async     #1
pymode_lint_async_updatetime #1000
pymode_lint_checkers  ['pyflakes', 'pep8', 'mccabe']
pymode_lint_comment_symbol  CC
pymode_lint_cwindow   #1
pymode_lint_docs_symbol  DD
pymode_lint_error_symbol  EE
pymode_lint_ignore    []
pymode_lint_info_symbol  II
pymode_lint_message   #1
pymode_lint_on_fly    #0
pymode_lint_on_write  #1
pymode_lint_options_mccabe {'complexity': 12}
pymode_lint_options_pep257 {}
pymode_lint_options_pep8 {'max_line_length': 79}
pymode_lint_options_pyflakes {'builtins': '_'}
pymode_lint_options_pylint {'max-line-length': 79}
pymode_lint_pyflakes_symbol  FF
pymode_lint_select    []
pymode_lint_signs     #1
pymode_lint_sort      []
pymode_lint_todo_symbol  WW
pymode_lint_unmodified #0
pymode_lint_visual_symbol  RR
pymode_motion         #1
pymode_options        #1
pymode_options_colorcolumn #1
pymode_options_max_line_length #79
pymode_paths          []
pymode_python          python3
pymode_quickfix_maxheight #6
pymode_quickfix_minheight #3
pymode_rope           #0
pymode_run            #1
pymode_run_bind        <leader>r
pymode_trim_whitespaces #1
pymode_version         0.9.4
pymode_virtualenv     #1
pymode_virtualenv_enabled  
pymode_virtualenv_path  
pymode_warning        #1
-------------------------------------------------------------------------------
pymode debug msg 5: Git commit: 
551c9d473f269d3b1ef7354506af4485bb88ba2c
-------------------------------------------------------------------------------
pymode debug msg 6: End of pymode#debug#sysinfo
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/nick/.cache/dein/repos/github.com/python-mode/python-mode/pymode/lint.py", line 9, in <module>
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/nick/.cache/dein/repos/github.com/python-mode/python-mode/pymode/libs/pylama/lint/extensions.py", line 38, in <module>
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
    from pkg_resources import iter_entry_points
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/nick/.cache/dein/repos/github.com/python-mode/python-mode/pymode/libs/pkg_resources/__init__.py", line 3092, in <module>
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
    @_call_aside
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/nick/.cache/dein/repos/github.com/python-mode/python-mode/pymode/libs/pkg_resources/__init__.py", line 3078, in _call_aside
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
    f(*args, **kwargs)
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/nick/.cache/dein/repos/github.com/python-mode/python-mode/pymode/libs/pkg_resources/__init__.py", line 3117, in _initialize_master_working_set
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
    add_activation_listener(lambda dist: dist.activate())
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/nick/.cache/dein/repos/github.com/python-mode/python-mode/pymode/libs/pkg_resources/__init__.py", line 965, in subscribe
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
    callback(dist)
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/nick/.cache/dein/repos/github.com/python-mode/python-mode/pymode/libs/pkg_resources/__init__.py", line 3117, in <lambda>
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
    add_activation_listener(lambda dist: dist.activate())
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/nick/.cache/dein/repos/github.com/python-mode/python-mode/pymode/libs/pkg_resources/__init__.py", line 2636, in activate
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
    declare_namespace(pkg)
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/nick/.cache/dein/repos/github.com/python-mode/python-mode/pymode/libs/pkg_resources/__init__.py", line 2227, in declare_namespace
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
    _handle_ns(packageName, path_item)
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/nick/.cache/dein/repos/github.com/python-mode/python-mode/pymode/libs/pkg_resources/__init__.py", line 2173, in _handle_ns
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
    loader = importer.find_spec(packageName)
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
AttributeError: 'zipimport.zipimporter' object has no attribute 'find_spec'-- INSERT --


"foo.py" 
"foo.py" 1L, 12C written
-------------------------------------------------------------------------------
pymode debug msg 7: check code
[Pymode] Code checking is running ...
Error detected while processing function pymode#buffer_post_write[10]..pymode#lint#check:
line   11:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'code_check' is not defined
[Pymode] Code checking is completed. No errors found.-- INSERT --


"foo.py" 
"foo.py" 4L, 43C written
-------------------------------------------------------------------------------
pymode debug msg 8: check code
[Pymode] Code checking is running ...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'code_check' is not defined
[Pymode] Code checking is completed. No errors found.

  4 print os.path.cwd()
-------------------------------------------------------------------------------
pymode debug msg 9: Session history:
      #  cmd history
      1  messages
      2  edit foo.py
      4  w
>     5  q
-------------------------------------------------------------------------------
pymode debug msg 1: Starting debug on: 2018-11-14 12:50:17 with file /tmp/pymode_debug_file.txt
-------------------------------------------------------------------------------
pymode debug msg 2: Operating system: Linux
-------------------------------------------------------------------------------
pymode debug msg 3: Scriptnames:
  1: ~/.cache/dein/repos/github.com/python-mode/python-mode/debugvimrc.vim
  2: /usr/share/vim/vim81/plugin/getscriptPlugin.vim
  3: /usr/share/vim/vim81/plugin/gzip.vim
  4: /usr/share/vim/vim81/plugin/logiPat.vim
  5: /usr/share/vim/vim81/plugin/manpager.vim
  6: /usr/share/vim/vim81/plugin/matchparen.vim
  7: /usr/share/vim/vim81/plugin/netrwPlugin.vim
  8: /usr/share/vim/vim81/plugin/rrhelper.vim
  9: /usr/share/vim/vim81/plugin/spellfile.vim
 10: /usr/share/vim/vim81/plugin/tarPlugin.vim
 11: /usr/share/vim/vim81/plugin/tohtml.vim
 12: /usr/share/vim/vim81/plugin/vimballPlugin.vim
 13: /usr/share/vim/vim81/plugin/zipPlugin.vim
 14: ~/.cache/dein/repos/github.com/python-mode/python-mode/plugin/pymode.vim
 15: ~/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode.vim
 16: /usr/share/vim/vim81/filetype.vim
 17: /usr/share/vim/vimfiles/ftdetect/PKGBUILD.vim
 18: /usr/share/vim/vimfiles/ftdetect/dockerfile.vim
 19: /usr/share/vim/vimfiles/ftdetect/meson.vim
 20: /usr/share/vim/vimfiles/ftdetect/vagrantfile.vim
 21: /usr/share/vim/vim81/ftplugin.vim
 22: /usr/share/vim/vim81/ftplugin/python.vim
 23: ~/.cache/dein/repos/github.com/python-mode/python-mode/ftplugin/python/pymode.vim
 24: ~/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/virtualenv.vim
 25: ~/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/breakpoint.vim
 26: ~/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/debug.vim
-------------------------------------------------------------------------------
pymode debug msg 4: Pymode variables:
pymode                #1
pymode_breakpoint     #1
pymode_breakpoint_bind  <leader>b
pymode_breakpoint_cmd  import ipdb; ipdb.set_trace()  # XXX BREAKPOINT
pymode_debug          #1
pymode_debug_counter  #3
pymode_debug_tempfile  /tmp/pymode_debug_file.txt
pymode_doc            #1
pymode_doc_bind        K
pymode_doc_vertical   #0
pymode_folding        #0
pymode_folding_nest_limit #1000
pymode_folding_regex   ^\s*\%(class\|def\|async\s\+def\) .\+\(:\s\+\w\)\@!
pymode_indent         #1
pymode_init           #1
pymode_lint           #1
pymode_lint_async     #1
pymode_lint_async_updatetime #1000
pymode_lint_checkers  ['pyflakes', 'pep8', 'mccabe']
pymode_lint_comment_symbol  CC
pymode_lint_cwindow   #1
pymode_lint_docs_symbol  DD
pymode_lint_error_symbol  EE
pymode_lint_ignore    []
pymode_lint_info_symbol  II
pymode_lint_message   #1
pymode_lint_on_fly    #0
pymode_lint_on_write  #1
pymode_lint_options_mccabe {'complexity': 12}
pymode_lint_options_pep257 {}
pymode_lint_options_pep8 {'max_line_length': 79}
pymode_lint_options_pyflakes {'builtins': '_'}
pymode_lint_options_pylint {'max-line-length': 79}
pymode_lint_pyflakes_symbol  FF
pymode_lint_select    []
pymode_lint_signs     #1
pymode_lint_sort      []
pymode_lint_todo_symbol  WW
pymode_lint_unmodified #0
pymode_lint_visual_symbol  RR
pymode_motion         #1
pymode_options        #1
pymode_options_colorcolumn #1
pymode_options_max_line_length #79
pymode_paths          []
pymode_python          python3
pymode_quickfix_maxheight #6
pymode_quickfix_minheight #3
pymode_rope           #0
pymode_run            #1
pymode_run_bind        <leader>r
pymode_trim_whitespaces #1
pymode_version         0.9.4
pymode_virtualenv     #1
pymode_virtualenv_enabled  
pymode_virtualenv_path  
pymode_warning        #1
-------------------------------------------------------------------------------
pymode debug msg 5: Git commit: 
551c9d473f269d3b1ef7354506af4485bb88ba2c
-------------------------------------------------------------------------------
pymode debug msg 6: End of pymode#debug#sysinfo
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/nick/.cache/dein/repos/github.com/python-mode/python-mode/pymode/lint.py", line 9, in <module>
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/nick/.cache/dein/repos/github.com/python-mode/python-mode/pymode/libs/pylama/lint/extensions.py", line 38, in <module>
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
    from pkg_resources import iter_entry_points
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/nick/.cache/dein/repos/github.com/python-mode/python-mode/pymode/libs/pkg_resources/__init__.py", line 3092, in <module>
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
    @_call_aside
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/nick/.cache/dein/repos/github.com/python-mode/python-mode/pymode/libs/pkg_resources/__init__.py", line 3078, in _call_aside
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
    f(*args, **kwargs)
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/nick/.cache/dein/repos/github.com/python-mode/python-mode/pymode/libs/pkg_resources/__init__.py", line 3117, in _initialize_master_working_set
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
    add_activation_listener(lambda dist: dist.activate())
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/nick/.cache/dein/repos/github.com/python-mode/python-mode/pymode/libs/pkg_resources/__init__.py", line 965, in subscribe
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
    callback(dist)
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/nick/.cache/dein/repos/github.com/python-mode/python-mode/pymode/libs/pkg_resources/__init__.py", line 3117, in <lambda>
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
    add_activation_listener(lambda dist: dist.activate())
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/nick/.cache/dein/repos/github.com/python-mode/python-mode/pymode/libs/pkg_resources/__init__.py", line 2636, in activate
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
    declare_namespace(pkg)
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/nick/.cache/dein/repos/github.com/python-mode/python-mode/pymode/libs/pkg_resources/__init__.py", line 2227, in declare_namespace
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
    _handle_ns(packageName, path_item)
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/nick/.cache/dein/repos/github.com/python-mode/python-mode/pymode/libs/pkg_resources/__init__.py", line 2173, in _handle_ns
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
    loader = importer.find_spec(packageName)
Error detected while processing /home/nick/.cache/dein/repos/github.com/python-mode/python-mode/autoload/pymode/lint.vim:
line    1:
AttributeError: 'zipimport.zipimporter' object has no attribute 'find_spec'

"foo.py" 
"foo.py" 4L, 43C written
  4 print os.path.cwd()
-------------------------------------------------------------------------------
pymode debug msg 7: Session history:
      #  cmd history
>     1  wq%                ```           

**edit** updating with debuger

**Comment by diraol** [comment]
As this error is happening a lot, I'm centralizing all discussions under #972 .
Over there I've explained a little bit better the problem and also there is already some suggestions for tests.
