### ISSUE TITLE
"pylint" linter does not work

### ISSUE THREAD

**Issue by regisz** [python-mode/python-mode#962]
The `pylint` linter can not be loaded.
I tried to find the problem. Maybe pylama (`fmv1992/pylama` fork) does not support it basically. I found in the original repo the next [commit](https://github.com/klen/pylama/commit/7df0fb775fbfb536e498e31c5768af3b3770b1a7):  `Include pylint support into pylama by default.` It has not been merged yet into `fmv1992/pylama` fork (which is used by pymode).

### /tmp/pymode_debug_file.txt:
```
pymode_lint_visual_symbol  RR
pymode_motion         #1
pymode_options        #1
pymode_options_colorcolumn #1
pymode_options_max_line_length #79
pymode_paths          []
pymode_python          python3
pymode_quickfix_maxheight #6
pymode_quickfix_minheight #3
pymode_rope           #0
pymode_run            #1
pymode_run_bind        <leader>r
pymode_trim_whitespaces #1
pymode_version         0.9.4
pymode_virtualenv     #1
pymode_virtualenv_enabled¤¤
pymode_virtualenv_path¤¤
pymode_warning        #1
-------------------------------------------------------------------------------
pymode debug msg 5: Git commit:¤
95fdf8f072f6d83f8a78618ef2567fbfd1819b2e
-------------------------------------------------------------------------------
pymode debug msg 6: End of pymode#debug#sysinfo


[Pymode] Code checking is running ...
1542287532 ['pylint', 'pep8', 'mccabe', 'pyflakes'] []
Error detected while processing function pymode#lint#check:
line   11:
WARNING:root:Linter `pylint` not found.
1542287532 Namespace(abspath=False, concurrent=False, file_params={}, force=True, format='pycodestyle', hook=False, ignore=[], linters=[('pep8', <pylama.lint.pylama_pycodestyle.Linter object at 0x7fb5f6728b00>), ('mccabe', <pylama.lint.pylama_mccabe.Linter object at 0x7fb5f6728a90>), ('pyflakes', <pylama.lint.pylama_pyflakes.Linter object at 0x7fb5f54f9828>)], linters_params={}, options=None, paths=['/home/balage'], report=None, select=[], skip=[], sort=[], verbose=False) []
1542287532 Start code check:  [pydev/tss-release__devel/tss-release/tss_release/config/content_obtainers.py]
Checking params: {'linters': [], 'select': set(), 'ignore': set(), 'skip': False}
Run pep8 {'max_line_length': '79'}
Run mccabe {'complexity': '12'}
Run pyflakes {'builtins': '_'}
1542287532 Find errors:  [34]
[Pymode] Found 0 error(s) and 34 warning(s)

Messages maintainer: Bram Moolenaar <Bram@vim.org>
"~/pydev/tss-release__devel/tss-release/tss_release/config/content_obtainers.py" 279L, 8695C
-------------------------------------------------------------------------------
pymode debug msg 1: Starting debug on: 2018-11-15 14:11:58 with file /tmp/pymode_debug_file.txt
-------------------------------------------------------------------------------
pymode debug msg 2: Operating system: Linux
-------------------------------------------------------------------------------
pymode debug msg 3: Scriptnames:
-------------------------------------------------------------------------------
pymode debug msg 4: Pymode variables:
pymode                #1
pymode_breakpoint     #1
pymode_breakpoint_bind  <leader>b
pymode_breakpoint_cmd  import pdb; pdb.set_trace()  # XXX BREAKPOINT
pymode_debug          #1
pymode_debug_count
```
### Vim:
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 14 2018 10:39:17)
Included patches: 1-526
Compiled by balage@dev12
Big version without GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     +tag_old_static
+arabic            +farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    -tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
-balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    -gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               -perl              +vartabs
-clipboard         +jumplist          +persistent_undo   +vertsplit
+cmdline_compl     +keymap            +postscript        +virtualedit
+cmdline_hist      +lambda            +printer           +visual
+cmdline_info      +langmap           -profile           +visualextra
+comments          +libcall           +python/dyn        +viminfo
+conceal           +linebreak         +python3/dyn       +vreplace
+cryptv            +lispindent        +quickfix          +wildignore
+cscope            +listcmds          +reltime           +wildmenu
+cursorbind        +localmap          +rightleft         +windows
+cursorshape       -lua               -ruby              +writebackup
+dialog_con        +menu              +scrollbind        -X11
+diff              +mksession         +signs             -xfontset
+digraphs          +modify_fname      +smartindent       -xim
-dnd               +mouse             +startuptime       -xpm
-ebcdic            -mouseshape        +statusline        -xsmp
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_clipboard
+eval              -mouse_gpm         +syntax            -xterm_save
+ex_extra          -mouse_jsbterm     +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/home/balage/.local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim        -lm -ltinfo -lnsl    -ldl
```
### lsb_release -a
```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.5 (stretch)
Release:        9.5
Codename:       stretch
```

**Comment by diraol** [comment]
@regisz Can you try my fork, please? if it works I'll merge into here.

https://github.com/diraol/python-mode

**Comment by regisz** [comment]
Ok, I used your repo (developer branch), but it has another error.

```
balage@dev12:~/.vim/bundle/python-mode$ git branch -vv
* develop 551c9d473f [origin/develop] Merge pull request #950 from riher/fix/py3-importlib
```
But I have to use a patch by https://github.com/python-mode/python-mode/issues/958#issuecomment-437857300 .

```
balage@dev12:~/.vim/bundle/python-mode/submodules/pylama$ git remote -v
diraol  git@github.com:diraol/python-mode.git (fetch)
diraol  git@github.com:diraol/python-mode.git (push)
klen    git@github.com:klen/pylama.git (fetch)
klen    git@github.com:klen/pylama.git (push)
origin  https://github.com/fmv1992/pylama (fetch)
origin  https://github.com/fmv1992/pylama (push)
```
```
balage@dev12:~/.vim/bundle/python-mode/submodules/pylama$ git branch -vv
  develop        c01c803980 [origin/develop] Merge remote-tracking branch 'klen/develop' into develop
* develop_diraol 58bc0c444f [diraol/develop] Add pylama submodule from original repo
```
```
balage@dev12:~$ python3 --version
Python 3.5.3
balage@dev12:~$ python --version
Python 2.7.13
```
```
-------------------------------------------------------------------------------
pymode debug msg 1: Starting debug on: 2018-11-16 08:29:04 with file /tmp/pymode_debug_file.txt
-------------------------------------------------------------------------------
pymode debug msg 2: Operating system: Linux
-------------------------------------------------------------------------------
pymode debug msg 3: Scriptnames:
  1: ~/.vim/bundle/python-mode/debugvimrc.vim
  2: ~/.local/share/vim/vim81/plugin/getscriptPlugin.vim
  3: ~/.local/share/vim/vim81/plugin/gzip.vim
  4: ~/.local/share/vim/vim81/plugin/logiPat.vim
  5: ~/.local/share/vim/vim81/plugin/manpager.vim
  6: ~/.local/share/vim/vim81/plugin/matchparen.vim
  7: ~/.local/share/vim/vim81/plugin/netrwPlugin.vim
  8: ~/.local/share/vim/vim81/plugin/rrhelper.vim
  9: ~/.local/share/vim/vim81/plugin/spellfile.vim
 10: ~/.local/share/vim/vim81/plugin/tarPlugin.vim
 11: ~/.local/share/vim/vim81/plugin/tohtml.vim
 12: ~/.local/share/vim/vim81/plugin/vimballPlugin.vim
 13: ~/.local/share/vim/vim81/plugin/zipPlugin.vim
 14: ~/.vim/bundle/python-mode/plugin/pymode.vim
 15: ~/.vim/bundle/python-mode/autoload/pymode.vim
 16: ~/.local/share/vim/vim81/filetype.vim
 17: ~/.local/share/vim/vim81/ftplugin.vim
 18: ~/.local/share/vim/vim81/ftplugin/python.vim
 19: ~/.vim/bundle/python-mode/ftplugin/python/pymode.vim
 20: ~/.vim/bundle/python-mode/autoload/pymode/virtualenv.vim
 21: ~/.vim/bundle/python-mode/autoload/pymode/breakpoint.vim
 22: ~/.vim/bundle/python-mode/autoload/pymode/debug.vim
-------------------------------------------------------------------------------
pymode debug msg 4: Pymode variables:
pymode                #1
pymode_breakpoint     #1
pymode_breakpoint_bind  <leader>b
pymode_breakpoint_cmd  import pdb; pdb.set_trace()  # XXX BREAKPOINT
pymode_debug          #1
pymode_debug_counter  #3
pymode_debug_tempfile  /tmp/pymode_debug_file.txt
pymode_doc            #1
pymode_doc_bind        K
pymode_doc_vertical   #0
pymode_folding        #0
pymode_folding_nest_limit #1000
pymode_folding_regex   ^\s*\%(class\|def\|async\s\+def\) .\+\(:\s\+\w\)\@!
pymode_indent         #1
pymode_init           #1
pymode_lint           #1
pymode_lint_async     #1
pymode_lint_async_updatetime #1000
pymode_lint_checkers  ['pyflakes', 'pep8', 'mccabe']
pymode_lint_comment_symbol  CC
pymode_lint_cwindow   #1
pymode_lint_docs_symbol  DD
pymode_lint_error_symbol  EE
pymode_lint_ignore    []
pymode_lint_info_symbol  II
pymode_lint_message   #1
pymode_lint_on_fly    #0
pymode_lint_on_write  #1
pymode_lint_options_mccabe {'complexity': 12}
pymode_lint_options_pep257 {}
pymode_lint_options_pep8 {'max_line_length': 79}
pymode_lint_options_pyflakes {'builtins': '_'}
pymode_lint_options_pylint {'max-line-length': 79}
pymode_lint_pyflakes_symbol  FF
pymode_lint_select    []
pymode_lint_signs     #1
pymode_lint_sort      []
pymode_lint_todo_symbol  WW
pymode_lint_unmodified #0
pymode_lint_visual_symbol  RR
pymode_motion         #1
pymode_options        #1
pymode_options_colorcolumn #1
pymode_options_max_line_length #79
pymode_paths          []
pymode_python          python3
pymode_quickfix_maxheight #6
pymode_quickfix_minheight #3
pymode_rope           #0
pymode_run            #1
pymode_run_bind        <leader>r
pymode_trim_whitespaces #1
pymode_version         0.9.4
pymode_virtualenv     #1
pymode_virtualenv_enabled¤¤
pymode_virtualenv_path¤¤
pymode_warning        #1
-------------------------------------------------------------------------------
pymode debug msg 5: Git commit:¤
551c9d473f269d3b1ef7354506af4485bb88ba2c
-------------------------------------------------------------------------------
pymode debug msg 6: End of pymode#debug#sysinfo
Error detected while processing /home/balage/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Error detected while processing /home/balage/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing /home/balage/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/balage/.vim/bundle/python-mode/pymode/lint.py", line 9, in <module>
Error detected while processing /home/balage/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Error detected while processing /home/balage/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
ImportError: No module named 'pylama.lint.extensions'

Messages maintainer: Bram Moolenaar <Bram@vim.org>
"~/pydev/tss-release__devel/tss-release/tss_release/config/content_obtainers.py" 279L, 8695C
-------------------------------------------------------------------------------
pymode debug msg 1: Starting debug on: 2018-11-16 08:29:04 with file /tmp/pymode_debug_file.txt
-------------------------------------------------------------------------------
pymode debug msg 2: Operating system: Linux
-------------------------------------------------------------------------------
pymode debug msg 3: Scriptnames:
-------------------------------------------------------------------------------
pymode debug msg 4: Pymode variables:
pymode                #1
pymode_breakpoint     #1
pymode_breakpoint_bind  <leader>b
pymode_breakpoint_cmd  import pdb; pdb.set_trace()  # XXX BREAKPOINT
pymode_debug          #1
pymode_debug_counter  #3
pymode_debug_tempfile  /tmp/pymode_debug_file.txt
pymode_doc            #1
pymode_doc_bind        K
pymode_doc_vertical   #0
pymode_folding        #0
pymode_folding_nest_limit #1000
pymode_folding_regex   ^\s*\%(class\|def\|async\s\+def\) .\+\(:\s\+\w\)\@
```

**Comment by diraol** [comment]
@regisz from the log output you are running 

> pymode debug msg 5: Git commit:¤
> 551c9d473f269d3b1ef7354506af4485bb88ba2c

Which is the develop version for this repo, not from my fork.

Or there is something missing in the content you have shared with us.

**Comment by regisz** [comment]
Sorry, I used your repo instead of pylama, not python-mode :).
So, I used now your "python-mode".
I got the next error:
```
-------------------------------------------------------------------------------
pymode debug msg 1: Starting debug on: 2018-11-19 11:34:06 with file /tmp/pymode_debug_file.txt
-------------------------------------------------------------------------------
pymode debug msg 2: Operating system: Linux
-------------------------------------------------------------------------------
pymode debug msg 3: Scriptnames:
  1: ~/.vim/bundle/python-mode/debugvimrc.vim
  2: ~/.local/share/vim/vim81/plugin/getscriptPlugin.vim
  3: ~/.local/share/vim/vim81/plugin/gzip.vim
  4: ~/.local/share/vim/vim81/plugin/logiPat.vim
  5: ~/.local/share/vim/vim81/plugin/manpager.vim
  6: ~/.local/share/vim/vim81/plugin/matchparen.vim
  7: ~/.local/share/vim/vim81/plugin/netrwPlugin.vim
  8: ~/.local/share/vim/vim81/plugin/rrhelper.vim
  9: ~/.local/share/vim/vim81/plugin/spellfile.vim
 10: ~/.local/share/vim/vim81/plugin/tarPlugin.vim
 11: ~/.local/share/vim/vim81/plugin/tohtml.vim
 12: ~/.local/share/vim/vim81/plugin/vimballPlugin.vim
 13: ~/.local/share/vim/vim81/plugin/zipPlugin.vim
 14: ~/.vim/bundle/python-mode/plugin/pymode.vim
 15: ~/.vim/bundle/python-mode/autoload/pymode.vim
 16: ~/.local/share/vim/vim81/filetype.vim
 17: ~/.local/share/vim/vim81/ftplugin.vim
 18: ~/.local/share/vim/vim81/ftplugin/python.vim
 19: ~/.vim/bundle/python-mode/ftplugin/python/pymode.vim
 20: ~/.vim/bundle/python-mode/autoload/pymode/virtualenv.vim
 21: ~/.vim/bundle/python-mode/autoload/pymode/breakpoint.vim
 22: ~/.vim/bundle/python-mode/autoload/pymode/debug.vim
-------------------------------------------------------------------------------
pymode debug msg 4: Pymode variables:
pymode                #1
pymode_breakpoint     #1
pymode_breakpoint_bind  <leader>b
pymode_breakpoint_cmd¤¤
pymode_debug          #1
pymode_debug_counter  #3
pymode_debug_tempfile  /tmp/pymode_debug_file.txt
pymode_doc            #1
pymode_doc_bind        K
pymode_doc_vertical   #0
pymode_folding        #0
pymode_folding_nest_limit #1000
pymode_folding_regex   ^\s*\%(class\|def\|async\s\+def\) .\+\(:\s\+\w\)\@!
pymode_indent         #1
pymode_init           #1
pymode_lint           #1
pymode_lint_async     #1
pymode_lint_async_updatetime #1000
pymode_lint_checkers  ['pyflakes', 'pep8', 'mccabe']
pymode_lint_comment_symbol  CC
pymode_lint_cwindow   #1
pymode_lint_docs_symbol  DD
pymode_lint_error_symbol  EE
pymode_lint_ignore    []
pymode_lint_info_symbol  II
pymode_lint_message   #1
pymode_lint_on_fly    #0
pymode_lint_on_write  #1
pymode_lint_options_mccabe {'complexity': 12}
pymode_lint_options_pep257 {}
pymode_lint_options_pep8 {'max_line_length': 79}
pymode_lint_options_pyflakes {'builtins': '_'}
pymode_lint_options_pylint {'max-line-length': 79}
pymode_lint_pyflakes_symbol  FF
pymode_lint_select    []
pymode_lint_signs     #1
pymode_lint_sort      []
pymode_lint_todo_symbol  WW
pymode_lint_unmodified #0
pymode_lint_visual_symbol  RR
pymode_motion         #1
pymode_options        #1
pymode_options_colorcolumn #1
pymode_options_max_line_length #79
pymode_paths          []
pymode_python          python3
pymode_quickfix_maxheight #6
pymode_quickfix_minheight #3
pymode_rope           #0
pymode_run            #1
pymode_run_bind        <leader>r
pymode_trim_whitespaces #1
pymode_version         0.9.4
pymode_virtualenv     #1
pymode_virtualenv_enabled¤¤
pymode_virtualenv_path¤¤
pymode_warning        #1
-------------------------------------------------------------------------------
pymode debug msg 5: Git commit:¤
58bc0c444f2a5acd34fa13ee43d2bc508597c62e
-------------------------------------------------------------------------------
pymode debug msg 6: End of pymode#debug#sysinfo
Error detected while processing /home/balage/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Error detected while processing /home/balage/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing /home/balage/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/balage/.vim/bundle/python-mode/pymode/lint.py", line 9, in <module>
Error detected while processing /home/balage/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Error detected while processing /home/balage/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
ImportError: No module named 'pylama'

Messages maintainer: Bram Moolenaar <Bram@vim.org>
"~/pydev/tss-release__devel/tss-release/tss_release/config/content_obtainers.py" 279L, 8695C
Error detected while processing function pymode#breakpoint#init:
line   29:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: No module named 'pymode.libs.six'
-------------------------------------------------------------------------------
pymode debug msg 1: Starting debug on: 2018-11-19 11:34:06 with file /tmp/pymode_debug_file.txt
-------------------------------------------------------------------------------
pymode debug msg 2: Operating system: Linux
-------------------------------------------------------------------------------
pymode debug msg 3: Scriptnames:
-------------------------------------------------------------------------------
pymode debug msg 4: Pymode variables:
pymode                #1
pymode_breakpoint     #1
pymode_breakpoint_bind  <leader>b
pymode_breakpoint_cmd¤¤
pymode_debug          #1
pymode_debug_counter  #3
pymode_debug_tempfile  /tmp/pymode_debug_file.txt
pymode_doc            #1
pymode_doc_bind        K
pymode_doc_vertical   #0
pymode_folding        #0
pymode_folding
```

**Comment by diraol** [comment]
@regisz please, try updating and see if it works now.

**Comment by diraol** [comment]
Hi @AnasR7 Can you share with us the info describe in the [Troubleshooting](https://github.com/python-mode/python-mode#troubleshootingdebugging)  section of our project?
