### ISSUE TITLE
Error detected while processing function provider#python3#Call (Linux)

### ISSUE THREAD

**Issue by John-P** [python-mode/python-mode#973]
When I try to open a .py file I get this error. The non development branch (master) works until I save, then I get a different error. However, on the development branch I get this error whenever I open a python file. Using vim-plug and python3.

Traceback:
```
pymode debug msg 6: End of pymode#debug#sysinfo
Error detected while processing function provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/john/.local/share/nvim/plugged/python-mode/pymode/lint.py", line 9, in <module>
    from pylama.lint.extensions import LINTERS
  File "/home/john/.local/share/nvim/plugged/python-mode/pymode/libs/pylama/lint/extensions.py", line
 44, in <module>
    from pylama.lint.pylama_pylint import Linter
  File "/home/john/.local/share/nvim/plugged/python-mode/pymode/libs/pylama/lint/pylama_pylint.py", l
ine 5, in <module>
    from astroid import MANAGER
  File "/home/john/.local/share/nvim/plugged/python-mode/pymode/libs/astroid/__init__.py", line 62, i
n <module>
    from astroid.nodes import *
  File "/home/john/.local/share/nvim/plugged/python-mode/pymode/libs/astroid/nodes.py", line 23, in <
module>
    from astroid.node_classes import (
  File "/home/john/.local/share/nvim/plugged/python-mode/pymode/libs/astroid/node_classes.py", line 3
7, in <module>
    from astroid import bases
  File "/home/john/.local/share/nvim/plugged/python-mode/pymode/libs/astroid/bases.py", line 29, in <
module>
    objectmodel = util.lazy_import('interpreter.objectmodel')
  File "/home/john/.local/share/nvim/plugged/python-mode/pymode/libs/astroid/util.py", line 24, in la
zy_import
    return lazy_object_proxy.Proxy(
Error detected while processing function provider#python3#Call:
line   18:
AttributeError: module 'lazy_object_proxy' has no attribute 'Proxy'
```

Pymode Variables:
```
pymode                #1
pymode_breakpoint     #1
pymode_breakpoint_bind  <leader>b
pymode_breakpoint_cmd  import pdb; pdb.set_trace()  # XXX BREAKPOINT
pymode_debug          #1
pymode_debug_counter  #3
pymode_debug_tempfile
pymode_doc            #1
pymode_doc_bind        K
pymode_doc_vertical   #0
pymode_folding        #0
pymode_folding_nest_limit #1000
pymode_folding_regex   ^\s*\%(class\|def\|async\s\+def\) .\+\(:\s\+\w\)\@!
pymode_indent         #1
pymode_init           #1
pymode_lint           #1
pymode_lint_async     #1
pymode_lint_async_updatetime #1000
pymode_lint_checkers  ['pyflakes', 'pep8', 'mccabe']
pymode_lint_comment_symbol  CC
pymode_lint_cwindow   #1
pymode_lint_docs_symbol  DD
pymode_lint_error_symbol  EE
pymode_lint_ignore    []
pymode_lint_info_symbol  II
pymode_lint_message   #1
pymode_lint_on_fly    #0
pymode_lint_on_write  #1
pymode_lint_options_mccabe {'complexity': 12}
pymode_lint_options_pep257 {}
```

**Comment by diraol** [comment]
Hi @John-P can you give us the information required at https://github.com/python-mode/python-mode#troubleshootingdebugging ?

**Comment by agjohnson** [comment]
I'm also hitting this. Following debug instructions there is nothing in `:messages` with a path to the log file. For me, the error triggers on first key press opening a py file.

Outside debug mode, Pymode loads (?) but every feature results in an ascii encoding error for a mystery file -- ie, jumping to a definition, saving file

**Comment by makimat** [comment]
I'm hitting this too. Here's my pymode debugging output.

```

-------------------------------------------------------------------------------
pymode debug msg 1: Starting debug on: 2019-02-13 08:22:48 with file /tmp/makimat/pymode_debug_file.txt
-------------------------------------------------------------------------------
pymode debug msg 2: Operating system: Linux
-------------------------------------------------------------------------------
pymode debug msg 3: Scriptnames:
  1: ~/.vim/bundle/python-mode/debugvimrc.vim
  2: /usr/local/share/vim/vim81/plugin/getscriptPlugin.vim
  3: /usr/local/share/vim/vim81/plugin/gzip.vim
  4: /usr/local/share/vim/vim81/plugin/logiPat.vim
  5: /usr/local/share/vim/vim81/plugin/manpager.vim
  6: /usr/local/share/vim/vim81/plugin/matchparen.vim
  7: /usr/local/share/vim/vim81/plugin/netrwPlugin.vim
  8: /usr/local/share/vim/vim81/plugin/rrhelper.vim
  9: /usr/local/share/vim/vim81/plugin/spellfile.vim
 10: /usr/local/share/vim/vim81/plugin/tarPlugin.vim
 11: /usr/local/share/vim/vim81/plugin/tohtml.vim
 12: /usr/local/share/vim/vim81/plugin/vimballPlugin.vim
 13: /usr/local/share/vim/vim81/plugin/zipPlugin.vim
 14: ~/.vim/bundle/python-mode/plugin/pymode.vim
 15: ~/.vim/bundle/python-mode/autoload/pymode.vim
 16: /usr/local/share/vim/vim81/filetype.vim
 17: /usr/local/share/vim/vim81/ftplugin.vim
 18: /usr/local/share/vim/vim81/ftplugin/python.vim
 19: ~/.vim/bundle/python-mode/ftplugin/python/pymode.vim
 20: ~/.vim/bundle/python-mode/autoload/pymode/virtualenv.vim
 21: ~/.vim/bundle/python-mode/autoload/pymode/breakpoint.vim
 22: ~/.vim/bundle/python-mode/autoload/pymode/debug.vim
-------------------------------------------------------------------------------
pymode debug msg 4: Pymode variables:
pymode                #1
pymode_breakpoint     #1
pymode_breakpoint_bind  <leader>b
pymode_breakpoint_cmd  import pdb; pdb.set_trace()  # XXX BREAKPOINT
pymode_debug          #1
pymode_debug_counter  #3
pymode_debug_tempfile  /tmp/makimat/pymode_debug_file.txt
pymode_doc            #1
pymode_doc_bind        K
pymode_doc_vertical   #0
pymode_folding        #0
pymode_folding_nest_limit #1000
pymode_folding_regex   ^\s*\%(class\|def\|async\s\+def\) .\+\(:\s\+\w\)\@!
pymode_indent         #1
pymode_init           #1
pymode_lint           #1
pymode_lint_async     #1
pymode_lint_async_updatetime #1000
pymode_lint_checkers  ['pyflakes', 'pep8', 'mccabe']
pymode_lint_comment_symbol  CC
pymode_lint_cwindow   #1
pymode_lint_docs_symbol  DD
pymode_lint_error_symbol  EE
pymode_lint_ignore    []
pymode_lint_info_symbol  II
pymode_lint_message   #1
pymode_lint_on_fly    #0
pymode_lint_on_write  #1
pymode_lint_options_mccabe {'complexity': 12}
pymode_lint_options_pep257 {}
pymode_lint_options_pep8 {'max_line_length': 79}
pymode_lint_options_pyflakes {'builtins': '_'}
pymode_lint_options_pylint {'max-line-length': 79}
pymode_lint_pyflakes_symbol  FF
pymode_lint_select    []
pymode_lint_signs     #1
pymode_lint_sort      []
pymode_lint_todo_symbol  WW
pymode_lint_unmodified #0
pymode_lint_visual_symbol  RR
pymode_motion         #1
pymode_options        #1
pymode_options_colorcolumn #1
pymode_options_max_line_length #79
pymode_paths          []
pymode_preview_height #12
pymode_preview_position  botright
pymode_python          python3
pymode_quickfix_maxheight #6
pymode_quickfix_minheight #3
pymode_rope           #0
pymode_run            #1
pymode_run_bind        <leader>r
pymode_trim_whitespaces #1
pymode_version         0.9.4
pymode_virtualenv     #1
pymode_virtualenv_enabled  
pymode_virtualenv_path  
pymode_warning        #1
-------------------------------------------------------------------------------
pymode debug msg 5: Git commit: 
d0d6cdf01494339e6addd0576cc0ab44d38d621d
-------------------------------------------------------------------------------
pymode debug msg 6: End of pymode#debug#sysinfo

Error detected while processing /home/makimat/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/makimat/.vim/bundle/python-mode/pymode/lint.py", line 9, in <module>
    from pylama.lint.extensions import LINTERS
  File "/home/makimat/.vim/bundle/python-mode/pymode/libs/pylama/lint/extensions.py", line 44, in <module>
    from pylama.lint.pylama_pylint import Linter
  File "/home/makimat/.vim/bundle/python-mode/pymode/libs/pylama/lint/pylama_pylint.py", line 5, in <module>
    from astroid import MANAGER
  File "/home/makimat/.vim/bundle/python-mode/pymode/libs/astroid/__init__.py", line 62, in <module>
    from astroid.nodes import *
  File "/home/makimat/.vim/bundle/python-mode/pymode/libs/astroid/nodes.py", line 23, in <module>
    from astroid.node_classes import (
  File "/home/makimat/.vim/bundle/python-mode/pymode/libs/astroid/node_classes.py", line 37, in <module>
    from astroid import bases
  File "/home/makimat/.vim/bundle/python-mode/pymode/libs/astroid/bases.py", line 29, in <module>
    objectmodel = util.lazy_import('interpreter.objectmodel')
  File "/home/makimat/.vim/bundle/python-mode/pymode/libs/astroid/util.py", line 24, in lazy_import
    return lazy_object_proxy.Proxy(
AttributeError: module 'lazy_object_proxy' has no attribute 'Proxy'
[Pymode] Code checking is running ...
Error detected while processing function pymode#lint#check:
line   11:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'code_check' is not defined
[Pymode] Code checking is completed. No errors found.

Messages maintainer: Bram Moolenaar <Bram@vim.org>
"path/to/mymodule.py" 323L, 14663C
-------------------------------------------------------------------------------
pymode debug msg 1: Starting debug on: 2019-02-13 08:22:48 with file /tmp/makimat/pymode_debug_file.txt
-------------------------------------------------------------------------------
pymode debug msg 2: Operating system: Linux
-------------------------------------------------------------------------------
pymode debug msg 3: Scriptnames:
-------------------------------------------------------------------------------
pymode debug msg 4: Pymode variables:
pymode                #1
pymode_breakpoint     #1
pymode_breakpoint_bind  <leader>b
pymode_breakpoint_cmd  import pdb; pdb.set_trace()  # XXX BREAKPOINT
pymode_debug          #1
pymode_debug_counter  #3
pymode_debug_tempfile  /tmp/makimat/pymode_debug_file.txt
pymode_doc            #1
pymode_doc_bind        K
pymode_doc_vertical   #0
pymode_folding        #0
pymode_folding_nest_limit #1000
pymode_folding_regex   ^\s*\%(class\|def\|async\s\+def\) .\+\(:\s\+\w\)\@!
pymode_indent         #1
pymode_init           #1
pymode_lint           #1
pymode_lint_async     #1
pymode_lint_async_updatetime #1000
pymode_lint_checkers  ['pyflakes', 'pep8', 'mccabe']
pymode_lint_comment_symbol  CC
pymode_lint_cwindow   #1
pymode_lint_docs_symbol  DD
pymode_lint_error_symbol  EE
pymode_lint_ignore    []
pymode_lint_info_symbol  II
pymode_lint_message   #1
pymode_lint_on_fly    #0
pymode_lint_on_write  #1
pymode_lint_options_mccabe {'complexity': 12}
pymode_lint_options_pep257 {}
pymode_lint_options_pep8 {'max_line_length': 79}
pymode_lint_options_pyflakes {'builtins': '_'}
pymode_lint_options_pylint {'max-line-length': 79}
pymode_lint_pyflakes_symbol  FF
pymode_lint_select    []
pymode_lint_signs     #1
pymode_lint_sort      []
pymode_lint_todo_symbol  WW
pymode_lint_unmodified #0
pymode_lint_visual_symbol  RR
pymode_motion         #1
pymode_options        #1
pymode_options_colorcolumn #1
pymode_options_max_line_length #79
pymode_paths          []
pymode_preview_height #12
pymode_preview_position  botright
pymode_python          python3
pymode_quickfix_maxheight #6
pymode_quickfix_minheight #3
pymode_rope           #0
pymode_run            #1
pymode_run_bind        <leader>r
pymode_trim_whitespaces #1
pymode_version         0.9.4
pymode_virtualenv     #1
pymode_virtualenv_enabled  
pymode_virtualenv_path  
pymode_warning        #1
-------------------------------------------------------------------------------
pymode debug msg 5: Git commit: 
d0d6cdf01494339e6addd0576cc0ab44d38d621d
-------------------------------------------------------------------------------
pymode debug msg 6: End of pymode#debug#sysinfo
Error detected while processing /home/makimat/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/makimat/.vim/bundle/python-mode/pymode/lint.py", line 9, in <module>
    from pylama.lint.extensions import LINTERS
  File "/home/makimat/.vim/bundle/python-mode/pymode/libs/pylama/lint/extensions.py", line 44, in <module>
    from pylama.lint.pylama_pylint import Linter
  File "/home/makimat/.vim/bundle/python-mode/pymode/libs/pylama/lint/pylama_pylint.py", line 5, in <module>
    from astroid import MANAGER
  File "/home/makimat/.vim/bundle/python-mode/pymode/libs/astroid/__init__.py", line 62, in <module>
    from astroid.nodes import *
  File "/home/makimat/.vim/bundle/python-mode/pymode/libs/astroid/nodes.py", line 23, in <module>
    from astroid.node_classes import (
  File "/home/makimat/.vim/bundle/python-mode/pymode/libs/astroid/node_classes.py", line 37, in <module>
    from astroid import bases
  File "/home/makimat/.vim/bundle/python-mode/pymode/libs/astroid/bases.py", line 29, in <module>
    objectmodel = util.lazy_import('interpreter.objectmodel')
  File "/home/makimat/.vim/bundle/python-mode/pymode/libs/astroid/util.py", line 24, in lazy_import
    return lazy_object_proxy.Proxy(
AttributeError: module 'lazy_object_proxy' has no attribute 'Proxy'
Error detected while processing function pymode#lint#check:
line   11:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Name
```

**Comment by diraol** [comment]
Hi @makimat,
can you provide you `vimrc`, share the outpuit of `vim --version`, and a way to reproduce the error locally (like a python file with a sample code and the commands you execute to get the error)?

**Comment by makimat** [comment]
You can find it from here: https://github.com/makimat/pymode-test

Let me know if any further information would be necessary. And thanks a lot for helping on the issue!

**Comment by makimat** [comment]
Sorry for bothering with this issue. I deleted and reinstalled python-mode with Vundle and now `:PymodeLint` works again without errors. I can't see any other reason for this than some `__pycache__` dirs under python-mode that might've been used and python3 version being upgraded in my env in between.

Hopefully this finding will help others stumbling into the same issue: either delete all `__pycache__`'s from your python-mode installation or just re-install the whole bundle.

**Comment by diraol** [comment]
No problem at all @makimat ! =)

Pycache is indeed a recurrent problem. That's why I've added a note in our [Troubleshooting](https://github.com/python-mode/python-mode/blob/develop/readme.md#troubleshootingdebugging) section about it and how to delete all cache files. ;)
