### ISSUE TITLE
Error detect while processing lint.vim on python3 

### ISSUE THREAD

**Issue by AnasR7** [python-mode/python-mode#976]
i have annoying problem when i opened python files, i got this error
![screenshot_2018-12-30_00-28-07](https://user-images.githubusercontent.com/23519166/50540859-46c41400-0bcc-11e9-8489-60e3a1f5e5be.png)

i have tried this #959, and this #844, also tried using git submodule update --init --recursive
and i got same error.

can you help me ?, thanks...

**Comment by diraol** [comment]
Hi @AnasR7 Can you share with us the info describe in the [Troubleshooting](https://github.com/python-mode/python-mode#troubleshootingdebugging)  section of our project?

**Comment by AnasR7** [comment]
> Hi @AnasR7 Can you share with us the info describe in the [Troubleshooting](https://github.com/python-mode/python-mode#troubleshootingdebugging) section of our project?

Thanks for fast respond...
sure 
```
E518: Unknown option: messages

Messages maintainer: Bram Moolenaar <Bram@vim.org>
"tuts-3.py" 0L, 0C
-------------------------------------------------------------------------------
pymode debug msg 1: Starting debug on: 2018-12-30 02:15:27 with file /tmp/pymode_debug_file.txt
-------------------------------------------------------------------------------
pymode debug msg 2: Operating system: Linux
-------------------------------------------------------------------------------
pymode debug msg 3: Scriptnames:
-------------------------------------------------------------------------------
pymode debug msg 4: Pymode variables:
pymode                #1
pymode_breakpoint     #1
pymode_breakpoint_bind  <leader>b
pymode_breakpoint_cmd  import pdb; pdb.set_trace()  # XXX BREAKPOINT
pymode_debug          #1
pymode_debug_counter  #3
pymode_debug_tempfile  /tmp/pymode_debug_file.txt
pymode_doc            #1
pymode_doc_bind        K
pymode_doc_vertical   #0
pymode_folding        #0
pymode_folding_nest_limit #1000
pymode_folding_regex   ^\s*\%(class\|def\|async\s\+def\) .\+\(:\s\+\w\)\@!
pymode_indent         #1
pymode_init           #1
pymode_lint           #1
pymode_lint_async     #1
pymode_lint_async_updatetime #1000
pymode_lint_checkers  ['pyflakes', 'pep8', 'mccabe']
pymode_lint_comment_symbol  CC
pymode_lint_cwindow   #1
pymode_lint_docs_symbol  DD
pymode_lint_error_symbol  EE
pymode_lint_ignore    []
pymode_lint_info_symbol  II
pymode_lint_message   #1
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/ftplugin/python/pymode.vim:
line  250:
Interrupted
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/anasr/.vim_runtime/plugged/python-mode/pymode/lint.py", line 9, in <module>
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/anasr/.vim_runtime/plugged/python-mode/pymode/libs/pylama/lint/extensions.py", line 44, in <module>
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.pylama_pylint import Linter
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/anasr/.vim_runtime/plugged/python-mode/pymode/libs/pylama/lint/pylama_pylint.py", line 5, in <module>
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    from astroid import MANAGER
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/anasr/.vim_runtime/plugged/python-mode/pymode/libs/astroid/__init__.py", line 62, in <module>
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    from astroid.nodes import *
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/anasr/.vim_runtime/plugged/python-mode/pymode/libs/astroid/nodes.py", line 23, in <module>
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    from astroid.node_classes import (
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/anasr/.vim_runtime/plugged/python-mode/pymode/libs/astroid/node_classes.py", line 37, in <module>
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    from astroid import bases
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/anasr/.vim_runtime/plugged/python-mode/pymode/libs/astroid/bases.py", line 33, in <module>
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    MANAGER = manager.AstroidManager()
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/anasr/.vim_runtime/plugged/python-mode/pymode/libs/astroid/util.py", line 25, in <lambda>
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    lambda: importlib.import_module('.' + module_name, 'astroid'))
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    return _bootstrap._gcd_import(name[level:], package, level)
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/anasr/.vim_runtime/plugged/python-mode/pymode/libs/astroid/manager.py", line 24, in <module>
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    from astroid.interpreter._import import spec
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/anasr/.vim_runtime/plugged/python-mode/pymode/libs/astroid/interpreter/_import/spec.py", line 27, in <module>
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    from . import util
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/anasr/.vim_runtime/plugged/python-mode/pymode/libs/astroid/interpreter/_import/util.py", line 4, in <module>
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    import pkg_resources
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/anasr/.vim_runtime/plugged/python-mode/pymode/libs/pkg_resources/__init__.py", line 3092, in <module>
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    @_call_aside
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/anasr/.vim_runtime/plugged/python-mode/pymode/libs/pkg_resources/__init__.py", line 3078, in _call_aside
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    f(*args, **kwargs)
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/anasr/.vim_runtime/plugged/python-mode/pymode/libs/pkg_resources/__init__.py", line 3117, in _initialize_master_working_set
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    add_activation_listener(lambda dist: dist.activate())
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/anasr/.vim_runtime/plugged/python-mode/pymode/libs/pkg_resources/__init__.py", line 965, in subscribe
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    callback(dist)
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/anasr/.vim_runtime/plugged/python-mode/pymode/libs/pkg_resources/__init__.py", line 3117, in <lambda>
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    add_activation_listener(lambda dist: dist.activate())
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/anasr/.vim_runtime/plugged/python-mode/pymode/libs/pkg_resources/__init__.py", line 2636, in activate
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    declare_namespace(pkg)
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/anasr/.vim_runtime/plugged/python-mode/pymode/libs/pkg_resources/__init__.py", line 2227, in declare_namespace
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    _handle_ns(packageName, path_item)
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/anasr/.vim_runtime/plugged/python-mode/pymode/libs/pkg_resources/__init__.py", line 2173, in _handle_ns
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    loader = importer.find_module(packageName)
Error detected while processing /home/anasr/.vim_runtime/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
AttributeError: module 'vim' has no attribute 'find_module'
E518: Unknown option: messages
```

**Comment by diraol** [comment]
hum.... 
Can you provide me the results for the following commands:

 - `uname -a`
 - `vim --version`
 - `python --version`
 - `python3 --version`

Oh, and open vim, then, while in "Normal mode", type
`:PymodePython import sys; print(sys.version_info)`

Whats the result for that?

**Comment by AnasR7** [comment]
> hum....
> Can you provide me the results for the following commands:
> 
>     * `uname -a`
> 
>     * `vim --version`
> 
>     * `python --version`
> 
>     * `python3 --version`
> 
> 
> Oh, and open vim, then, while in "Normal mode", type
> `:PymodePython import sys; print(sys.version_info)`
> 
> Whats the result for that?

uname -a
```
Linux user-pc 4.19.12-2-MANJARO #1 SMP PREEMPT Sun Dec 23 19:08:00 UTC 2018 x86_64 GNU/Linux
```
vim --version
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec  8 2018 11:23:48)
Included patches: 1-570
Compiled by Arch Linux
Huge version without GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     +tag_old_static
+arabic            +farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    +tcl/dyn
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               +perl/dyn          +vartabs
-clipboard         +jumplist          +persistent_undo   +vertsplit
+cmdline_compl     +keymap            +postscript        +virtualedit
+cmdline_hist      +lambda            +printer           +visual
+cmdline_info      +langmap           +profile           +visualextra
+comments          +libcall           +python/dyn        +viminfo
+conceal           +linebreak         +python3/dyn       +vreplace
+cryptv            +lispindent        +quickfix          +wildignore
+cscope            +listcmds          +reltime           +wildmenu
+cursorbind        +localmap          +rightleft         +windows
+cursorshape       +lua/dyn           +ruby/dyn          +writebackup
+dialog_con        +menu              +scrollbind        -X11
+diff              +mksession         +signs             -xfontset
+digraphs          +modify_fname      +smartindent       -xim
-dnd               +mouse             +startuptime       -xpm
-ebcdic            -mouseshape        +statusline        -xsmp
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_clipboard
+eval              +mouse_gpm         +syntax            -xterm_save
+ex_extra          -mouse_jsbterm     +tag_binary        
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.28/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim        -lm -ltinfo -lelf -lnsl    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.28/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.28/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm 
```
python --version
```
Python 3.7.1
```
python3 --version
```
Python 3.7.1
```
:PymodePython import sys; print(sys.version_info)
![screenshot_2018-12-30_10-15-15](https://user-images.githubusercontent.com/23519166/50544065-dd6bf180-0c1b-11e9-8f61-cde52d004d4c.png)

can you solve this error ? @diraol  thanks.

**Comment by AnasR7** [comment]
i close this issues i know what hapenned because find_module no longer use it.

thanks..
 sorry for my misunderstanding.
