### ISSUE TITLE
python-mode fails on vim startup

### ISSUE THREAD

**Issue by thevorpalblade** [python-mode/python-mode#982]
Hello! When opening a .py file with vim, with python-mode enabled, I just get a screen full of error messages (reproduced below). This is on a fresh install of python-mode (although it started happening after I'd been using python-mode for years without incident).

I have run `git submodule update --init --recursive` in the appropriate directory, and have `let g:pymode_python = 'python3'`set in my .vimrc. I'm managing the plugin with Vundle.

My vim is version 8.1 compiled with +python/dyn and +python3/dyn, and I'm using Python 3.7.2.

Here is the debug log, generated as you suggested in the troubleshooting section:

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
-------------------------------------------------------------------------------
pymode debug msg 1: Starting debug on: 2019-01-10 14:58:42 with file /tmp/pymode_debug_file.txt
-------------------------------------------------------------------------------
pymode debug msg 2: Operating system: Linux
-------------------------------------------------------------------------------
pymode debug msg 3: Scriptnames:
-------------------------------------------------------------------------------
pymode debug msg 4: Pymode variables:
pymode                #1
pymode_breakpoint     #1
pymode_breakpoint_bind  <leader>b
pymode_breakpoint_cmd  import ipdb; ipdb.set_trace()  # XXX BREAKPOINT
pymode_debug          #1
pymode_debug_counter  #3
pymode_debug_tempfile  /tmp/pymode_debug_file.txt
pymode_doc            #1
pymode_doc_bind        K
pymode_doc_vertical   #0
pymode_folding        #0
pymode_folding_nest_limit #1000
pymode_folding_regex   ^\s*\%(class\|def\|async\s\+def\) .\+\(:\s\+\w\)\@!
pymode_indent         #1
pymode_init           #1
pymode_lint           #1
pymode_lint_async     #1
pymode_lint_async_updatetime #1000
pymode_lint_checkers  ['pyflakes', 'pep8', 'mccabe']
pymode_lint_comment_symbol  CC
pymode_lint_cwindow   #1
pymode_lint_docs_symbol  DD
pymode_lint_error_symbol  EE
pymode_lint_ignore    []
pymode_lint_info_symbol  II
pymode_lint_message   #1
pymode_lint_on_fly    #0
pymode_lint_on_write  #1
pymode_lint_options_mccabe {'complexity': 12}
pymode_lint_options_pep257 {}
pymode_lint_options_pep8 {'max_line_length': 79}
pymode_lint_options_pyflakes {'builtins': '_'}
pymode_lint_options_pylint {'max-line-length': 79}
pymode_lint_pyflakes_symbol  FF
pymode_lint_select    []
pymode_lint_signs     #1
pymode_lint_sort      []
pymode_lint_todo_symbol  WW
pymode_lint_unmodified #0
pymode_lint_visual_symbol  RR
pymode_motion         #1
pymode_options        #1
pymode_options_colorcolumn #1
pymode_options_max_line_length #79
pymode_paths          []
pymode_preview_height #12
pymode_preview_position  botright
pymode_python          python3
pymode_quickfix_maxheight #6
pymode_quickfix_minheight #3
pymode_rope           #0
pymode_run            #1
pymode_run_bind        <leader>r
pymode_trim_whitespaces #1
pymode_version         0.9.4
pymode_virtualenv     #1
pymode_virtualenv_enabled  
pymode_virtualenv_path  
pymode_warning        #1
-------------------------------------------------------------------------------
pymode debug msg 5: Git commit: 
ac97c66a8b65a5811a67e4e6e326f4f6feb037d9
-------------------------------------------------------------------------------
pymode debug msg 6: End of pymode#debug#sysinfo
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/matthew/.vim/bundle/python-mode/pymode/lint.py", line 9, in <module>
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/matthew/.vim/bundle/python-mode/pymode/libs/pylama/lint/extensions.py", line 44, in <module>
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.pylama_pylint import Linter
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/matthew/.vim/bundle/python-mode/pymode/libs/pylama/lint/pylama_pylint.py", line 5, in <module>
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from astroid import MANAGER
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/matthew/.vim/bundle/python-mode/pymode/libs/astroid/__init__.py", line 62, in <module>
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from astroid.nodes import *
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/matthew/.vim/bundle/python-mode/pymode/libs/astroid/nodes.py", line 23, in <module>
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from astroid.node_classes import (
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/matthew/.vim/bundle/python-mode/pymode/libs/astroid/node_classes.py", line 37, in <module>
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from astroid import bases
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/matthew/.vim/bundle/python-mode/pymode/libs/astroid/bases.py", line 33, in <module>
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    MANAGER = manager.AstroidManager()
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/matthew/.vim/bundle/python-mode/pymode/libs/astroid/util.py", line 25, in <lambda>
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    lambda: importlib.import_module('.' + module_name, 'astroid'))
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    return _bootstrap._gcd_import(name[level:], package, level)
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/matthew/.vim/bundle/python-mode/pymode/libs/astroid/manager.py", line 24, in <module>
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from astroid.interpreter._import import spec
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/matthew/.vim/bundle/python-mode/pymode/libs/astroid/interpreter/_import/spec.py", line 27, in <module>
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from . import util
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/matthew/.vim/bundle/python-mode/pymode/libs/astroid/interpreter/_import/util.py", line 4, in <module>
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    import pkg_resources
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/matthew/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 3092, in <module>
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    @_call_aside
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/matthew/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 3078, in _call_aside
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    f(*args, **kwargs)
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/matthew/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 3117, in _initialize_master_working_set
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    add_activation_listener(lambda dist: dist.activate())
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/matthew/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 965, in subscribe
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    callback(dist)
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/matthew/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 3117, in <lambda>
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    add_activation_listener(lambda dist: dist.activate())
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/matthew/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 2636, in activate
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    declare_namespace(pkg)
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/matthew/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 2227, in declare_namespace
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    _handle_ns(packageName, path_item)
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/matthew/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 2173, in _handle_ns
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    loader = importer.find_module(packageName)
Error detected while processing /home/matthew/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
AttributeError: module 'vim' has no attribute 'find_module'
```

**Comment by diraol** [comment]
Hi @thevorpalblade !
Thanks for the info you provided.

Unfortunately this is a recurrent problem we have been seeing in the project and it is being handled (or at least we are trying to) in the issue #972.
The error you are seeing derives from the same points from that issue.
So I'll close this issue for us to concentrate over there ok?

As I said over there, I know that we have this problem, but I haven't had much free time to find a way to fix it, so any help will be much appreciated!

Tks!

**Comment by kevinkirkup** [comment]
Seeing this same issue:

```

-------------------------------------------------------------------------------
pymode debug msg 1: Starting debug on: 2020-05-27 15:05:45 with file /var/folders/0w/kzhd3y3s46s_0n9lllqb3p7w0000gq/T/pymode_debug_file.txt
-------------------------------------------------------------------------------
pymode debug msg 2: Operating system: Darwin
-------------------------------------------------------------------------------
pymode debug msg 3: Scriptnames:
  1: ~/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/debugvimrc.vim
  2: /usr/local/Cellar/macvim/8.2-163_2/MacVim.app/Contents/Resources/vim/runtime/plugin/getscriptPlugin.vim
  3: /usr/local/Cellar/macvim/8.2-163_2/MacVim.app/Contents/Resources/vim/runtime/plugin/gzip.vim
  4: /usr/local/Cellar/macvim/8.2-163_2/MacVim.app/Contents/Resources/vim/runtime/plugin/logiPat.vim
  5: /usr/local/Cellar/macvim/8.2-163_2/MacVim.app/Contents/Resources/vim/runtime/plugin/manpager.vim
  6: /usr/local/Cellar/macvim/8.2-163_2/MacVim.app/Contents/Resources/vim/runtime/plugin/matchparen.vim
  7: /usr/local/Cellar/macvim/8.2-163_2/MacVim.app/Contents/Resources/vim/runtime/plugin/netrwPlugin.vim
  8: /usr/local/Cellar/macvim/8.2-163_2/MacVim.app/Contents/Resources/vim/runtime/plugin/rrhelper.vim
  9: /usr/local/Cellar/macvim/8.2-163_2/MacVim.app/Contents/Resources/vim/runtime/plugin/spellfile.vim
 10: /usr/local/Cellar/macvim/8.2-163_2/MacVim.app/Contents/Resources/vim/runtime/plugin/tarPlugin.vim
 11: /usr/local/Cellar/macvim/8.2-163_2/MacVim.app/Contents/Resources/vim/runtime/plugin/tohtml.vim
 12: /usr/local/Cellar/macvim/8.2-163_2/MacVim.app/Contents/Resources/vim/runtime/plugin/vimballPlugin.vim
 13: /usr/local/Cellar/macvim/8.2-163_2/MacVim.app/Contents/Resources/vim/runtime/plugin/zipPlugin.vim
 14: ~/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/plugin/pymode.vim
 15: ~/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/autoload/pymode.vim
 16: /usr/local/Cellar/macvim/8.2-163_2/MacVim.app/Contents/Resources/vim/runtime/filetype.vim
 17: /usr/local/Cellar/macvim/8.2-163_2/MacVim.app/Contents/Resources/vim/runtime/ftplugin.vim
 18: /usr/local/Cellar/macvim/8.2-163_2/MacVim.app/Contents/Resources/vim/runtime/ftplugin/python.vim
 19: ~/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/ftplugin/python/pymode.vim
 20: ~/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/autoload/pymode/virtualenv.vim
 21: ~/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/autoload/pymode/breakpoint.vim
 22: ~/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/autoload/pymode/debug.vim
-------------------------------------------------------------------------------
pymode debug msg 4: Pymode variables:
pymode                #1
pymode_breakpoint     #1
pymode_breakpoint_bind  <leader>b
pymode_breakpoint_cmd  import pdb; pdb.set_trace()  # XXX BREAKPOINT
pymode_debug          #1
pymode_debug_counter  #3
pymode_debug_tempfile  /var/folders/0w/kzhd3y3s46s_0n9lllqb3p7w0000gq/T/pymode_debug_file.txt
pymode_doc            #1
pymode_doc_bind        K
pymode_doc_vertical   #0
pymode_folding        #0
pymode_folding_nest_limit #1000
pymode_folding_regex   ^\s*\%(class\|def\|async\s\+def\) .\+\(:\s\+\w\)\@!
pymode_indent         #1
pymode_init           #1
pymode_lint           #1
pymode_lint_async     #1
pymode_lint_async_updatetime #1000
pymode_lint_checkers  ['pyflakes', 'pep8', 'mccabe']
pymode_lint_comment_symbol  CC
pymode_lint_cwindow   #1
pymode_lint_docs_symbol  DD
pymode_lint_error_symbol  EE
pymode_lint_ignore    []
pymode_lint_info_symbol  II
pymode_lint_message   #1
pymode_lint_on_fly    #0
pymode_lint_on_write  #1
pymode_lint_options_mccabe {'complexity': 12}
pymode_lint_options_pep257 {}
pymode_lint_options_pep8 {'max_line_length': 79}
pymode_lint_options_pyflakes {'builtins': '_'}
pymode_lint_options_pylint {'max-line-length': 79}
pymode_lint_pyflakes_symbol  FF
pymode_lint_select    []
pymode_lint_signs     #1
pymode_lint_sort      []
pymode_lint_todo_symbol  WW
pymode_lint_unmodified #0
pymode_lint_visual_symbol  RR
pymode_motion         #1
pymode_options        #1
pymode_options_colorcolumn #1
pymode_options_max_line_length #79
pymode_paths          []
pymode_preview_height #12
pymode_preview_position  botright
pymode_python          python3
pymode_quickfix_maxheight #6
pymode_quickfix_minheight #3
pymode_rope           #0
pymode_run            #1
pymode_run_bind        <leader>r
pymode_trim_whitespaces #1
pymode_version         0.10.0
pymode_virtualenv     #1
pymode_virtualenv_enabled  
pymode_virtualenv_path  
pymode_warning        #1
-------------------------------------------------------------------------------
pymode debug msg 5: Git commit: 
b207a1c9d9f76e3104a300c2aeb26c147b98811f
-------------------------------------------------------------------------------
pymode debug msg 6: End of pymode#debug#sysinfo

Messages maintainer: Bram Moolenaar <Bram@vim.org>
"~/Documents/repos/pureport/ansible/roles/kato_supported_connections/library/pureport_supported_connection_facts.py" 95L, 2528C
-------------------------------------------------------------------------------
pymode debug msg 1: Starting debug on: 2020-05-27 15:05:45 with file /var/folders/0w/kzhd3y3s46s_0n9lllqb3p7w0000gq/T/pymode_debug_file.txt
-------------------------------------------------------------------------------
pymode debug msg 2: Operating system: Darwin
-------------------------------------------------------------------------------
pymode debug msg 3: Scriptnames:
-------------------------------------------------------------------------------
pymode debug msg 4: Pymode variables:
pymode                #1
pymode_breakpoint     #1
pymode_breakpoint_bind  <leader>b
pymode_breakpoint_cmd  import pdb; pdb.set_trace()  # XXX BREAKPOINT
pymode_debug          #1
pymode_debug_counter  #3
pymode_debug_tempfile  /var/folders/0w/kzhd3y3s46s_0n9lllqb3p7w0000gq/T/pymode_debug_file.txt
pymode_doc            #1
pymode_doc_bind        K
pymode_doc_vertical   #0
pymode_folding        #0
pymode_folding_nest_limit #1000
pymode_folding_regex   ^\s*\%(class\|def\|async\s\+def\) .\+\(:\s\+\w\)\@!
pymode_indent         #1
pymode_init           #1
pymode_lint           #1
pymode_lint_async     #1
pymode_lint_async_updatetime #1000
pymode_lint_checkers  ['pyflakes', 'pep8', 'mccabe']
pymode_lint_comment_symbol  CC
pymode_lint_cwindow   #1
pymode_lint_docs_symbol  DD
pymode_lint_error_symbol  EE
pymode_lint_ignore    []
pymode_lint_info_symbol  II
pymode_lint_message   #1
pymode_lint_on_fly    #0
pymode_lint_on_write  #1
pymode_lint_options_mccabe {'complexity': 12}
pymode_lint_options_pep257 {}
pymode_lint_options_pep8 {'max_line_length': 79}
pymode_lint_options_pyflakes {'builtins': '_'}
pymode_lint_options_pylint {'max-line-length': 79}
pymode_lint_pyflakes_symbol  FF
pymode_lint_select    []
pymode_lint_signs     #1
pymode_lint_sort      []
pymode_lint_todo_symbol  WW
pymode_lint_unmodified #0
pymode_lint_visual_symbol  RR
pymode_motion         #1
pymode_options        #1
pymode_options_colorcolumn #1
pymode_options_max_line_length #79
pymode_paths          []
pymode_preview_height #12
pymode_preview_position  botright
pymode_python          python3
pymode_quickfix_maxheight #6
pymode_quickfix_minheight #3
pymode_rope           #0
pymode_run            #1
pymode_run_bind        <leader>r
pymode_trim_whitespaces #1
pymode_version         0.10.0
pymode_virtualenv     #1
pymode_virtualenv_enabled  
pymode_virtualenv_path  
pymode_warning        #1
-------------------------------------------------------------------------------
pymode debug msg 5: Git commit: 
b207a1c9d9f76e3104a300c2aeb26c147b98811f
-------------------------------------------------------------------------------
pymode debug msg 6: End of pymode#debug#sysinfo
Error detected while processing /Users/kevinkirkup/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Error detected while processing /Users/kevinkirkup/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing /Users/kevinkirkup/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/kevinkirkup/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/pymode/lint.py", line 9, in <module>
Error detected while processing /Users/kevinkirkup/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Error detected while processing /Users/kevinkirkup/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/kevinkirkup/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/pymode/libs/pylama/lint/extensions.py", line 44, in <module>
Error detected while processing /Users/kevinkirkup/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.pylama_pylint import Linter
Error detected while processing /Users/kevinkirkup/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/kevinkirkup/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/pymode/libs/pylama/lint/pylama_pylint.py", line 5, in <module>
Error detected while processing /Users/kevinkirkup/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from astroid import MANAGER
Error detected while processing /Users/kevinkirkup/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/kevinkirkup/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/pymode/libs/astroid/__init__.py", line 62, in <module>
Error detected while processing /Users/kevinkirkup/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from astroid.nodes import *
Error detected while processing /Users/kevinkirkup/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/kevinkirkup/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/pymode/libs/astroid/nodes.py", line 23, in <module>
Error detected while processing /Users/kevinkirkup/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from astroid.node_classes import (
Error detected while processing /Users/kevinkirkup/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/kevinkirkup/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/pymode/libs/astroid/node_classes.py", line 37, in <module>
Error detected while processing /Users/kevinkirkup/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from astroid import bases
Error detected while processing /Users/kevinkirkup/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/kevinkirkup/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/pymode/libs/astroid/bases.py", line 29, in <module>
Error detected while processing /Users/kevinkirkup/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    objectmodel = util.lazy_import('interpreter.objectmodel')
Error detected while processing /Users/kevinkirkup/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/kevinkirkup/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/pymode/libs/astroid/util.py", line 24, in lazy_import
Error detected while processing /Users/kevinkirkup/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    return lazy_object_proxy.Proxy(
Error detected while processing /Users/kevinkirkup/.homesick/repos/spicy-vim/home/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
AttributeError: module 'lazy_object_proxy' has no attribute 'Proxy'recording @j

  2  
-------------------------------------------------------------------------------
pymode debug msg 7: Session history:
      #  cmd history
      1  e ~/Documents/repos/pureport/ansible/roles/kato_supported_connections/library/pureport_supported_connection_facts.py
      2  messages
>     3  qa
```

**Comment by diraol** [comment]
Hi @kevinkirkup, this doesn't seems to be the same issue. Please, open a new issue with your setup and outputs.
