### ISSUE TITLE
Failed to begin python-mode

### ISSUE THREAD

**Issue by elliottcstr** [python-mode/python-mode#992]
```
[Pymode] Activate virtualenv: ~/workdir/env
1550689479 let g:pymode_virtualenv_enabled = "~/workdir/env" []
-------------------------------------------------------------------------------
pymode debug msg 1: Starting debug on: 2019-02-20 14:04:39 with file /tmp/pymode_debug_file.txt
-------------------------------------------------------------------------------
pymode debug msg 2: Operating system: Linux
-------------------------------------------------------------------------------
pymode debug msg 3: Scriptnames:
-------------------------------------------------------------------------------
pymode debug msg 4: Pymode variables:
pymode                #1
pymode_breakpoint     #1
pymode_breakpoint_bind  <leader>b
pymode_breakpoint_cmd  import ipdb; ipdb.set_trace()  # XXX BREAKPOINT
pymode_debug          #1
pymode_debug_counter  #3
pymode_debug_tempfile  /tmp/pymode_debug_file.txt
pymode_doc            #1
pymode_doc_bind        K
pymode_doc_vertical   #0
pymode_folding        #0
pymode_folding_nest_limit #1000
pymode_folding_regex   ^\s*\%(class\|def\|async\s\+def\) .\+\(:\s\+\w\)\@!
pymode_indent         #1
pymode_init           #1
pymode_lint           #1
pymode_lint_async     #1
pymode_lint_async_updatetime #1000
pymode_lint_checkers  ['pyflakes', 'pep8', 'mccabe']
pymode_lint_comment_symbol  CC
pymode_lint_cwindow   #1
pymode_lint_docs_symbol  DD
pymode_lint_error_symbol  EE
pymode_lint_ignore    []
pymode_lint_info_symbol  II
pymode_lint_message   #1
pymode_lint_on_fly    #0
pymode_lint_on_write  #1
pymode_lint_options_mccabe {'complexity': 12}
pymode_lint_options_pep257 {}
pymode_lint_options_pep8 {'max_line_length': 79}
pymode_lint_options_pyflakes {'builtins': '_'}
pymode_lint_options_pylint {'max-line-length': 79}
pymode_lint_pyflakes_symbol  FF
pymode_lint_select    []
pymode_lint_signs     #1
pymode_lint_sort      []
pymode_lint_todo_symbol  WW
pymode_lint_unmodified #0
pymode_lint_visual_symbol  RR
pymode_motion         #1
pymode_options        #1
pymode_options_colorcolumn #1
pymode_options_max_line_length #79
pymode_paths          []
pymode_preview_height #12
pymode_preview_position  botright
pymode_python          python3
pymode_quickfix_maxheight #6
pymode_quickfix_minheight #3
pymode_rope           #0
pymode_run            #1
pymode_run_bind        <leader>r
pymode_trim_whitespaces #1
pymode_version         0.9.4
pymode_virtualenv     #1
pymode_virtualenv_enabled  ~/workdir/env
pymode_virtualenv_path  ~/workdir/env
pymode_warning        #1
-------------------------------------------------------------------------------
pymode debug msg 5: Git commit:
81a4f6e71a210e6120dd99f5bff6a33023a1323f
-------------------------------------------------------------------------------
pymode debug msg 6: End of pymode#debug#sysinfo
Error detected while processing ~/.vim/pack/my-plugins/start/python-mode/autoload/pymode/lint.vim:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "~/.vim/pack/my-plugins/start/python-mode/pymode/lint.py", line 9, in <module>
    from pylama.lint.extensions import LINTERS
  File "~/.vim/pack/my-plugins/start/python-mode/pymode/libs/pylama/lint/extensions.py", line 44, in <module>
    from pylama.lint.pylama_pylint import Linter
  File "~/.vim/pack/my-plugins/start/python-mode/pymode/libs/pylama/lint/pylama_pylint.py", line 5, in <module>
    from astroid import MANAGER
  File "~/.vim/pack/my-plugins/start/python-mode/pymode/libs/astroid/__init__.py", line 62, in <module>
    from astroid.nodes import *
  File "~/.vim/pack/my-plugins/start/python-mode/pymode/libs/astroid/nodes.py", line 23, in <module>
    from astroid.node_classes import (
  File "~/.vim/pack/my-plugins/start/python-mode/pymode/libs/astroid/node_classes.py", line 37, in <module>
    from astroid import bases
  File "~/.vim/pack/my-plugins/start/python-mode/pymode/libs/astroid/bases.py", line 33, in <module>
    MANAGER = manager.AstroidManager()
  File "~/.vim/pack/my-plugins/start/python-mode/pymode/libs/astroid/util.py", line 25, in <lambda>
    lambda: importlib.import_module('.' + module_name, 'astroid'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "~/.vim/pack/my-plugins/start/python-mode/pymode/libs/astroid/manager.py", line 24, in <module>
    from astroid.interpreter._import import spec
  File "~/.vim/pack/my-plugins/start/python-mode/pymode/libs/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "~/.vim/pack/my-plugins/start/python-mode/pymode/libs/astroid/interpreter/_import/util.py", line 4, in <module>
    import pkg_resources
  File "~/.vim/pack/my-plugins/start/python-mode/pymode/libs/pkg_resources/__init__.py", line 3112, in <module>
    @_call_aside
  File "~/.vim/pack/my-plugins/start/python-mode/pymode/libs/pkg_resources/__init__.py", line 3098, in _call_aside
    f(*args, **kwargs)
  File "~/.vim/pack/my-plugins/start/python-mode/pymode/libs/pkg_resources/__init__.py", line 3137, in _initialize_master_working_set
    add_activation_listener(lambda dist: dist.activate())
  File "~/.vim/pack/my-plugins/start/python-mode/pymode/libs/pkg_resources/__init__.py", line 965, in subscribe
    callback(dist)
  File "~/.vim/pack/my-plugins/start/python-mode/pymode/libs/pkg_resources/__init__.py", line 3137, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "~/.vim/pack/my-plugins/start/python-mode/pymode/libs/pkg_resources/__init__.py", line 2656, in activate
    declare_namespace(pkg)
  File "~/.vim/pack/my-plugins/start/python-mode/pymode/libs/pkg_resources/__init__.py", line 2247, in declare_namespace
    _handle_ns(packageName, path_item)
  File "~/.vim/pack/my-plugins/start/python-mode/pymode/libs/pkg_resources/__init__.py", line 2214, in _handle_ns
    loader.load_module(packageName)
AttributeError: 'ModuleSpec' object has no attribute 'load_module'
```

**Comment by elliottcstr** [comment]
Maybe this?

```diff
diff --git a/pymode/libs/pkg_resources/__init__.py b/pymode/libs/pkg_resources/__init__.py
index ead2b6a..bec9867 100644
--- a/pymode/libs/pkg_resources/__init__.py
+++ b/pymode/libs/pkg_resources/__init__.py
@@ -2188,7 +2188,7 @@ def _handle_ns(packageName, path_item):
         # As `find_module` is deprecated for newer python, we try `find_spec`
         # first.
         try:
-            loader = importer.find_spec(packageName)
+            loader = importer.find_spec(packageName).loader
         except AttributeError:
             loader = importer.find_module(packageName)
     else:

```

**Comment by diraol** [comment]
@elliottcstr which python version are you using?
(open vim and execute `:python import sys; print(sys.version_info)` (or `python3 import sys; print(sys.version_info`).

Also, can you provide the result to `vim --version`?

**Comment by elliottcstr** [comment]
@diraol 

```
$ python3 -c "import sys; print(sys.version_info)"
sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)
```

```
$ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
Included patches: 1-1453
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               -perl              +vertsplit
-clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           -python            +vreplace
+conceal           +linebreak         +python3           +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       -lua               -ruby              -X11
+dialog_con        +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             -xim
+digraphs          +modify_fname      +smartindent       -xpm
-dnd               +mouse             +startuptime       -xsmp
-ebcdic            -mouseshape        +statusline        -xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              +mouse_gpm         +syntax
+ex_extra          -mouse_jsbterm     +tag_binary
+extra_search      +mouse_netterm     +tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-NQEcoP/vim-8.0.1453=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl     -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lm
```

**Comment by elliottcstr** [comment]
The patch above should fix the issue.
[find_spec()](https://docs.python.org/3/library/importlib.html#importlib.abc.MetaPathFinder.find_spec) returns a [spec](https://docs.python.org/3/glossary.html#term-module-spec) not a loader

**Comment by diraol** [comment]
@elliottcstr Your suggestion indeed make sense.

But I have to say that I have no idea why this was not failing "generally". This is a change that has been made very recently, and we have had many users testing it.

Regarding the "`python import sys; print(sys.version_info)`", I was expecting you to execute it inside vim, not in your shell, so we can see which python version is being loaded by vim.

But I think this is not that important ...

I'll just ping some other folks to see if your suggestion make sense for them too and if it will not break something else. ;)

**Comment by elliottcstr** [comment]
@diraol 

Apologies I had to use
`:python3 import sys; print(sys.version_info)`
not
`:python import sys; print(sys.version_info)`
in vim but the results are inconsequential:
`sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)`

**Comment by zcodes** [comment]
as @elliottcstr mentioned above, here we should use find_spec().loader as find_spec just return a spec, but mostly, we should also check find_spec() returns None with no loader attribute, maybe code like below:

```python
try:
    spec = importer.find_spec(packageName)
    if spec:
        loader = spec.loader
    else:
        return None
```

the code below the `loader = importer.find_spec...` in most most most case never run, that why the code currently passed testing by many users. until now, I have no idea how to let the code `loader.load_module(packageName)` run ...

**Comment by diraol** [comment]
@elliottcstr, no problem regarding python version ;)

@elliottcstr and @zcodes, I've added the proposed change! =) Check to see if it is everything ok.

**Comment by elliottcstr** [comment]
Looks great! Have been using today, and no issues, thanks for the speedy fix!

**Comment by zcodes** [comment]
@diraol everything ok !

**Comment by dbeniamine** [comment]
@diraol  in #972 you asked us to look at this issue, but I do not see which step I should do to try reproduce it.

I am currently using the develop branch, and python mode seems to be working just fine for me, tell me If you want me to test with some specific settings.

**Comment by diraol** [comment]
@dbeniamine We do not have any special test sequence (despite our test scripts, which I've executed myself in a clean environment, so, no need to run it).

I was just asking for you guys to update python-mode and try the common stuff you are used to do with it.

Btw, our current recommended branch is the `develop` one, so all ok. ;)

**Comment by dbeniamine** [comment]
Ok then it's all good and working for me :)
